# Copyright 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

# Code generated by scripts/generate_observability_redaction_catalog.py; DO NOT EDIT.
"""Immutable observability detector-catalog v1 configuration constants."""

DETECTOR_CATALOG_VERSION = 1
DETECTOR_GROUPS = (
    "credentials",
    "secrets",
    "pii",
)

DETECTOR_GROUP_MEMBERS = (
    (
        "credentials",
        (
            "credentials.api_token",
            "credentials.private_key",
            "credentials.authorization",
            "credentials.cookie",
            "credentials.connection_string",
        ),
    ),
    (
        "secrets",
        (
            "secrets.assignment",
            "secrets.high_entropy",
            "secrets.url_query",
            "secrets.cloud_account_identifier",
        ),
    ),
    (
        "pii",
        (
            "pii.email",
            "pii.telephone",
            "pii.national_identifier",
            "pii.payment_card",
            "pii.ip_address",
        ),
    ),
)

DETECTOR_IDS = (
    "credentials.api_token",
    "credentials.private_key",
    "credentials.authorization",
    "credentials.cookie",
    "credentials.connection_string",
    "secrets.assignment",
    "secrets.high_entropy",
    "secrets.url_query",
    "secrets.cloud_account_identifier",
    "pii.email",
    "pii.telephone",
    "pii.national_identifier",
    "pii.payment_card",
    "pii.ip_address",
)
