#!/usr/bin/env python3
# Copyright 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0
"""Generate the immutable Go detector-catalog table from the v8 YAML manifest."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "schemas/telemetry/v8/redaction/detector-catalog-v1.yaml"
GO_OUTPUT = ROOT / "internal/observability/redaction/catalog_generated.go"
PYTHON_OUTPUT = ROOT / "cli/defenseclaw/observability/detector_catalog_v1.py"
GROUPS = ("credentials", "secrets", "pii")


def quoted(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load() -> dict:
    document = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    if document.get("catalog_version") != 1:
        raise ValueError("catalog_version must be 1")
    groups = document.get("groups")
    detectors = document.get("detectors")
    if not isinstance(groups, list) or [g.get("token") for g in groups] != list(GROUPS):
        raise ValueError("groups must be ordered credentials, secrets, pii")
    if not isinstance(detectors, list) or len(detectors) != 14:
        raise ValueError("catalog v1 must contain exactly 14 detectors")
    ids: list[str] = []
    for position, entry in enumerate(detectors, 1):
        if entry.get("order") != position:
            raise ValueError(f"detector order must be contiguous at {position}")
        detector_id = entry.get("id")
        group = entry.get("group")
        if not isinstance(detector_id, str) or detector_id in ids:
            raise ValueError(f"invalid or duplicate detector id at {position}")
        if detector_id.split(".", 1)[0] != group:
            raise ValueError(f"detector {detector_id} does not belong to {group}")
        ids.append(detector_id)
    flattened = [detector_id for group in groups for detector_id in group["detector_ids"]]
    if flattened != ids:
        raise ValueError("ordered group membership must equal detector order")
    return document


def render(document: dict) -> str:
    lines = [
        "// Copyright 2026 Cisco Systems, Inc. and its affiliates",
        "//",
        "// Licensed under the Apache License, Version 2.0 (the \"License\");",
        "// SPDX-License-Identifier: Apache-2.0",
        "",
        "// Code generated by scripts/generate_observability_redaction_catalog.py; DO NOT EDIT.",
        "",
        "package redaction",
        "",
        "const generatedDetectorCatalogVersion = 1",
        "",
        "var generatedCatalogDefinitions = [...]catalogDefinition{",
    ]
    for entry in document["detectors"]:
        lines.extend([
            "\t{",
            f"\t\torder: {entry['order']},",
            f"\t\tgroup: DetectorGroup({quoted(entry['group'])}),",
            f"\t\tid: DetectorID({quoted(entry['id'])}),",
            f"\t\tlexicalGrammar: {quoted(entry['lexical_grammar'])},",
            f"\t\tsemanticValidator: {quoted(entry['semantic_validator'])},",
            f"\t\tinputContext: {quoted(entry['input_context'])},",
            f"\t\tcandidateBound: {entry['candidate_bound']},",
            f"\t\treplacementInterval: {quoted(entry['replacement_interval'])},",
            f"\t\tfixtureSet: {quoted(entry['fixture_set'])},",
            "\t},",
        ])
    lines.extend(["}", "", "var generatedGroupDefinitions = [...]groupDefinition{"])
    for group in document["groups"]:
        members = ", ".join(f"DetectorID({quoted(item)})" for item in group["detector_ids"])
        lines.append(f"\t{{token: DetectorGroup({quoted(group['token'])}), members: [5]DetectorID{{{members}}}}},")
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_python(document: dict) -> str:
    lines = [
        "# Copyright 2026 Cisco Systems, Inc. and its affiliates",
        "# SPDX-License-Identifier: Apache-2.0",
        "",
        "# Code generated by scripts/generate_observability_redaction_catalog.py; DO NOT EDIT.",
        '"""Immutable observability detector-catalog v1 configuration constants."""',
        "",
        "DETECTOR_CATALOG_VERSION = 1",
        "DETECTOR_GROUPS = (",
    ]
    lines.extend(f"    {json.dumps(group)}," for group in GROUPS)
    lines.extend([")", "", "DETECTOR_GROUP_MEMBERS = ("])
    for group in document["groups"]:
        lines.extend(["    (", f"        {json.dumps(group['token'])},", "        ("])
        lines.extend(f"            {json.dumps(detector_id)}," for detector_id in group["detector_ids"])
        lines.extend(["        ),", "    ),"])
    lines.extend([")", "", "DETECTOR_IDS = ("])
    lines.extend(f"    {json.dumps(entry['id'])}," for entry in document["detectors"])
    lines.extend([")", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        rendered_go = subprocess.run(
            ["gofmt"],
            input=render(load()),
            text=True,
            check=True,
            capture_output=True,
        ).stdout
        document = load()
        rendered_python = render_python(document)
    except (OSError, ValueError, yaml.YAMLError, subprocess.CalledProcessError) as exc:
        print(f"redaction catalog generation failed: {exc}", file=sys.stderr)
        return 1
    if args.check:
        for output, rendered in ((GO_OUTPUT, rendered_go), (PYTHON_OUTPUT, rendered_python)):
            if not output.exists() or output.read_text(encoding="utf-8") != rendered:
                print(f"generated redaction catalog is stale: {output}", file=sys.stderr)
                return 1
        return 0
    for output, rendered in ((GO_OUTPUT, rendered_go), (PYTHON_OUTPUT, rendered_python)):
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
