#!/usr/bin/env python3
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
"""Pure preflight for the complete generated telemetry Go candidate set.

This module owns no schema, renderer, filesystem, or publication behavior.  A
future Go API plan supplies the exact declaration keys and rendered bytes.  The
coordinator only proves that the complete in-memory candidate is internally
coherent before any caller is allowed to hand it to a publication transaction.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import re
from collections.abc import Sequence
from typing import Final

EXACT_GO_OUTPUT_PATHS: Final = (
    "internal/observability/zz_generated_telemetry_ids.go",
    "internal/observability/zz_generated_telemetry_catalog.go",
    "internal/observability/zz_generated_telemetry_producers.go",
    "internal/observability/zz_generated_telemetry_builders_genai.go",
    "internal/observability/zz_generated_telemetry_builders_security.go",
    "internal/observability/zz_generated_telemetry_builders_operations.go",
    "internal/observability/zz_generated_telemetry_builder_fixtures_test.go",
)
OWNERSHIP_MARKER: Final = b"// Code generated by DefenseClaw telemetry registry; DO NOT EDIT."
OUTPUT_MODE: Final = 0o644
MAX_HEADER_LINE_BYTES: Final = 128
MAX_HEADER_BYTES: Final = 512
MAX_DECLARATION_KEYS: Final = 100_000

_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_KEY_KIND = re.compile(r"^[a-z][a-z0-9_]{0,63}$")
_KEY_SOURCE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:/#-]{0,511}$")
_HEADER_FIELDS: Final = (
    "materialized_view_sha256",
    "candidate_render_index_sha256",
    "go_symbol_table_sha256",
)
_MANIFEST_DIGEST_DOMAIN: Final = b"DefenseClaw TelemetryGoOutputManifest v1\x00"
_OUTPUT_INVENTORY_DIGEST_DOMAIN: Final = b"DefenseClaw TelemetryGoOutputInventory v1\x00"
_DECLARATION_INVENTORY_DIGEST_DOMAIN: Final = b"DefenseClaw TelemetryGoDeclarationInventory v1\x00"


class GoOutputPreflightError(RuntimeError):
    """An in-memory generated Go candidate failed closed validation."""


@dataclasses.dataclass(frozen=True, slots=True, order=True)
class GoDeclarationKey:
    """One exact package-declaration identity supplied by the Go API plan."""

    kind: str
    source_id: str


@dataclasses.dataclass(frozen=True, slots=True)
class RenderedGoOutput:
    """One complete renderer result held only in memory."""

    path: str
    payload: bytes
    marker: bytes
    mode: int = OUTPUT_MODE


@dataclasses.dataclass(frozen=True, slots=True)
class GoFileDeclarationInventory:
    """The declaration keys assigned to one exact output by the Go API plan."""

    path: str
    declaration_keys: tuple[GoDeclarationKey, ...]


@dataclasses.dataclass(frozen=True, slots=True)
class ValidatedGoOutput:
    path: str
    payload: bytes
    marker: bytes
    mode: int
    payload_sha256: str
    declaration_keys: tuple[GoDeclarationKey, ...]


@dataclasses.dataclass(frozen=True, slots=True)
class GoManifestDigestMetadata:
    format_version: int
    materialized_view_sha256: str
    candidate_render_index_sha256: str
    go_symbol_table_sha256: str
    declaration_inventory_sha256: str
    output_inventory_sha256: str
    manifest_sha256: str


@dataclasses.dataclass(frozen=True, slots=True)
class GoOutputPreflightResult:
    outputs: tuple[ValidatedGoOutput, ...]
    metadata: GoManifestDigestMetadata


def _canonical_json_bytes(value: object) -> bytes:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"), sort_keys=True).encode("ascii")


def _sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _validated_digest(value: str, field: str) -> str:
    if not isinstance(value, str) or _SHA256.fullmatch(value) is None:
        raise GoOutputPreflightError(f"{field} is not a canonical SHA-256 digest")
    return value


def _validate_declaration_key(key: GoDeclarationKey) -> None:
    if not isinstance(key, GoDeclarationKey):
        raise GoOutputPreflightError("declaration inventory contains an invalid key")
    if _KEY_KIND.fullmatch(key.kind) is None or _KEY_SOURCE.fullmatch(key.source_id) is None:
        raise GoOutputPreflightError("declaration inventory contains a noncanonical key")


def canonical_go_header(
    materialized_view_sha256: str,
    candidate_render_index_sha256: str,
    go_symbol_table_sha256: str,
) -> bytes:
    """Return the only accepted bounded digest/ownership header."""

    digests = (
        _validated_digest(materialized_view_sha256, _HEADER_FIELDS[0]),
        _validated_digest(candidate_render_index_sha256, _HEADER_FIELDS[1]),
        _validated_digest(go_symbol_table_sha256, _HEADER_FIELDS[2]),
    )
    lines = [OWNERSHIP_MARKER]
    lines.extend(
        f"// defenseclaw-{field.replace('_', '-')}: {digest}".encode("ascii")
        for field, digest in zip(_HEADER_FIELDS, digests)
    )
    if any(len(line) > MAX_HEADER_LINE_BYTES for line in lines):
        raise GoOutputPreflightError("canonical generated Go header line exceeds its bound")
    header = b"\n".join(lines) + b"\n\n"
    if len(header) > MAX_HEADER_BYTES:
        raise GoOutputPreflightError("canonical generated Go header exceeds its bound")
    return header


def _parse_header(payload: bytes, marker: bytes) -> tuple[str, str, str]:
    boundary = payload.find(b"\n\n", 0, MAX_HEADER_BYTES + 1)
    if boundary < 0:
        raise GoOutputPreflightError("generated Go output has a missing or oversized canonical header")
    header = payload[: boundary + 2]
    if len(header) > MAX_HEADER_BYTES:
        raise GoOutputPreflightError("generated Go output header exceeds its bound")
    lines = header[:-2].split(b"\n")
    if len(lines) != 4 or lines[0] != marker or any(len(line) > MAX_HEADER_LINE_BYTES for line in lines):
        raise GoOutputPreflightError("generated Go output header is malformed")
    observed: list[str] = []
    for field, line in zip(_HEADER_FIELDS, lines[1:]):
        prefix = f"// defenseclaw-{field.replace('_', '-')}: ".encode("ascii")
        if not line.startswith(prefix):
            raise GoOutputPreflightError("generated Go output header is malformed")
        try:
            digest = line[len(prefix) :].decode("ascii")
        except UnicodeDecodeError as exc:
            raise GoOutputPreflightError("generated Go output header is malformed") from exc
        observed.append(_validated_digest(digest, field))
    if not payload[boundary + 2 :].startswith(b"package observability\n"):
        raise GoOutputPreflightError("generated Go output must declare package observability after its header")
    return observed[0], observed[1], observed[2]


def _validated_expected_keys(expected: Sequence[GoDeclarationKey]) -> frozenset[GoDeclarationKey]:
    if not isinstance(expected, Sequence) or isinstance(expected, (str, bytes, bytearray)):
        raise GoOutputPreflightError("expected declaration keys are not a bounded sequence")
    if len(expected) > MAX_DECLARATION_KEYS:
        raise GoOutputPreflightError("expected declaration-key inventory exceeds its safety bound")
    for key in expected:
        _validate_declaration_key(key)
    result = frozenset(expected)
    if len(result) != len(expected):
        raise GoOutputPreflightError("expected declaration-key inventory contains duplicates")
    return result


def _validate_file_inventory(
    inventories: Sequence[GoFileDeclarationInventory],
    expected_keys: frozenset[GoDeclarationKey],
) -> dict[str, tuple[GoDeclarationKey, ...]]:
    if not isinstance(inventories, Sequence) or isinstance(inventories, (str, bytes, bytearray)):
        raise GoOutputPreflightError("Go file declaration inventory is not a bounded sequence")
    if len(inventories) != len(EXACT_GO_OUTPUT_PATHS):
        raise GoOutputPreflightError("Go file declaration inventory must cover all seven exact paths")
    by_path: dict[str, tuple[GoDeclarationKey, ...]] = {}
    observed: list[GoDeclarationKey] = []
    for inventory in inventories:
        if not isinstance(inventory, GoFileDeclarationInventory):
            raise GoOutputPreflightError("Go file declaration inventory contains an invalid row")
        if inventory.path not in EXACT_GO_OUTPUT_PATHS:
            raise GoOutputPreflightError("Go file declaration inventory contains an extra path")
        if inventory.path in by_path:
            raise GoOutputPreflightError("Go file declaration inventory contains a duplicate path")
        if not isinstance(inventory.declaration_keys, tuple):
            raise GoOutputPreflightError("Go file declaration keys must be an immutable tuple")
        for key in inventory.declaration_keys:
            _validate_declaration_key(key)
        by_path[inventory.path] = inventory.declaration_keys
        observed.extend(inventory.declaration_keys)
    if set(by_path) != set(EXACT_GO_OUTPUT_PATHS):
        raise GoOutputPreflightError("Go file declaration inventory must cover all seven exact paths")
    if len(observed) != len(expected_keys) or len(set(observed)) != len(expected_keys):
        raise GoOutputPreflightError("Go declaration inventory contains a missing or duplicate declaration key")
    if frozenset(observed) != expected_keys:
        raise GoOutputPreflightError("Go declaration inventory does not cover the caller-expected exact keys")
    return by_path


def _declaration_inventory_document(
    inventory: dict[str, tuple[GoDeclarationKey, ...]],
) -> list[dict[str, object]]:
    return [
        {
            "path": path,
            "declarations": [{"kind": key.kind, "source_id": key.source_id} for key in inventory[path]],
        }
        for path in EXACT_GO_OUTPUT_PATHS
    ]


def preflight_go_outputs(
    outputs: Sequence[RenderedGoOutput],
    declaration_inventory: Sequence[GoFileDeclarationInventory],
    *,
    expected_declaration_keys: Sequence[GoDeclarationKey],
    materialized_view_sha256: str,
    candidate_render_index_sha256: str,
    go_symbol_table_sha256: str,
) -> GoOutputPreflightResult:
    """Validate a complete seven-file candidate (or the explicit empty set)."""

    expected_digests = (
        _validated_digest(materialized_view_sha256, _HEADER_FIELDS[0]),
        _validated_digest(candidate_render_index_sha256, _HEADER_FIELDS[1]),
        _validated_digest(go_symbol_table_sha256, _HEADER_FIELDS[2]),
    )
    expected_keys = _validated_expected_keys(expected_declaration_keys)
    if not isinstance(outputs, Sequence) or isinstance(outputs, (str, bytes, bytearray)):
        raise GoOutputPreflightError("generated Go outputs are not a bounded sequence")
    if len(outputs) not in {0, len(EXACT_GO_OUTPUT_PATHS)}:
        raise GoOutputPreflightError("generated Go output inventory must contain all seven exact paths or none")
    if not outputs:
        if declaration_inventory:
            raise GoOutputPreflightError("an empty Go candidate cannot carry a declaration/file inventory")
        empty_inventory = _canonical_json_bytes([])
        declaration_digest = _sha256(_DECLARATION_INVENTORY_DIGEST_DOMAIN + empty_inventory)
        output_digest = _sha256(_OUTPUT_INVENTORY_DIGEST_DOMAIN + empty_inventory)
        manifest_document = {
            "format_version": 1,
            "materialized_view_sha256": expected_digests[0],
            "candidate_render_index_sha256": expected_digests[1],
            "go_symbol_table_sha256": expected_digests[2],
            "declaration_inventory_sha256": declaration_digest,
            "output_inventory_sha256": output_digest,
        }
        manifest_digest = _sha256(_MANIFEST_DIGEST_DOMAIN + _canonical_json_bytes(manifest_document))
        return GoOutputPreflightResult(
            (),
            GoManifestDigestMetadata(1, *expected_digests, declaration_digest, output_digest, manifest_digest),
        )

    by_path: dict[str, RenderedGoOutput] = {}
    observed_headers: set[tuple[str, str, str]] = set()
    for output in outputs:
        if not isinstance(output, RenderedGoOutput):
            raise GoOutputPreflightError("generated Go output inventory contains an invalid row")
        if output.path not in EXACT_GO_OUTPUT_PATHS:
            raise GoOutputPreflightError("generated Go output inventory contains an extra internal path")
        if output.path in by_path:
            raise GoOutputPreflightError("generated Go output inventory contains a duplicate path")
        if not isinstance(output.payload, bytes):
            raise GoOutputPreflightError("generated Go output payload is not immutable bytes")
        if type(output.mode) is not int or output.mode != OUTPUT_MODE:
            raise GoOutputPreflightError("generated Go output mode is not 0644")
        if output.marker != OWNERSHIP_MARKER:
            raise GoOutputPreflightError("generated Go output ownership marker is not canonical")
        header = _parse_header(output.payload, output.marker)
        observed_headers.add(header)
        by_path[output.path] = output
    if set(by_path) != set(EXACT_GO_OUTPUT_PATHS):
        raise GoOutputPreflightError("generated Go output inventory must contain all seven exact paths or none")
    if len(observed_headers) != 1:
        raise GoOutputPreflightError("generated Go outputs carry mixed digest headers")
    if next(iter(observed_headers)) != expected_digests:
        raise GoOutputPreflightError("generated Go output digest headers are stale")

    inventory_by_path = _validate_file_inventory(declaration_inventory, expected_keys)
    declaration_document = _declaration_inventory_document(inventory_by_path)
    declaration_digest = _sha256(_DECLARATION_INVENTORY_DIGEST_DOMAIN + _canonical_json_bytes(declaration_document))
    validated: list[ValidatedGoOutput] = []
    output_document: list[dict[str, object]] = []
    for path in EXACT_GO_OUTPUT_PATHS:
        output = by_path[path]
        payload_digest = _sha256(output.payload)
        validated.append(
            ValidatedGoOutput(
                path,
                output.payload,
                output.marker,
                output.mode,
                payload_digest,
                inventory_by_path[path],
            )
        )
        output_document.append(
            {
                "path": path,
                "sha256": payload_digest,
                "mode": output.mode,
                "marker": output.marker.decode("ascii"),
            }
        )
    output_digest = _sha256(_OUTPUT_INVENTORY_DIGEST_DOMAIN + _canonical_json_bytes(output_document))
    manifest_document = {
        "format_version": 1,
        "materialized_view_sha256": expected_digests[0],
        "candidate_render_index_sha256": expected_digests[1],
        "go_symbol_table_sha256": expected_digests[2],
        "declaration_inventory_sha256": declaration_digest,
        "output_inventory_sha256": output_digest,
    }
    manifest_digest = _sha256(_MANIFEST_DIGEST_DOMAIN + _canonical_json_bytes(manifest_document))
    return GoOutputPreflightResult(
        tuple(validated),
        GoManifestDigestMetadata(1, *expected_digests, declaration_digest, output_digest, manifest_digest),
    )
