#!/usr/bin/env python3
# Copyright 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0
"""Test-only output driver for reduced telemetry compiler fixtures.

The compiler-focused fixture intentionally has fewer registry declarations than
the production candidate renderer accepts. This driver keeps those tests on the
real compiler and direct output writer while replacing only the renderer fanout
with one deterministic exact-inventory projection.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parents[3]
GENERATOR = ROOT / "scripts/generate_telemetry_registry.py"


def _load_generator() -> ModuleType:
    name = "telemetry_registry_manifest_test_driver_generator"
    spec = importlib.util.spec_from_file_location(name, GENERATOR)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load telemetry registry generator")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _fixture_outputs(generator: ModuleType, ir: object) -> dict[Path, bytes]:
    digest = ir.materialized_view.typed_canonical_json_sha256
    outputs = {
        Path(path): (
            json.dumps(
                {"artifact": path, "materialized_view_sha256": digest},
                sort_keys=True,
                separators=(",", ":"),
            )
            + "\n"
        ).encode()
        for path in generator.runtime_assets.LOGICAL_TO_ENCODED
    }
    outputs.update(
        {
            Path(path): (
                "// Code generated by DefenseClaw telemetry registry; DO NOT EDIT.\n"
                f"// materialized_view_sha256: {digest}\n"
                "package observability\n"
            ).encode()
            for path in generator.GO_CANDIDATE_OUTPUT_PATHS
        }
    )
    return outputs


def main(argv: list[str] | None = None) -> int:
    generator = _load_generator()
    generator.render_outputs = lambda ir: _fixture_outputs(generator, ir)
    return generator.main(argv)


if __name__ == "__main__":
    raise SystemExit(main())
