// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: facts.proto

package semanticpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseStatus int32

const (
	ParseStatus_PARSE_STATUS_UNSPECIFIED    ParseStatus = 0
	ParseStatus_PARSE_STATUS_NOT_APPLICABLE ParseStatus = 1
	ParseStatus_PARSE_STATUS_COMPLETE       ParseStatus = 2
	ParseStatus_PARSE_STATUS_PARTIAL        ParseStatus = 3
	ParseStatus_PARSE_STATUS_UNSUPPORTED    ParseStatus = 4
	ParseStatus_PARSE_STATUS_INVALID        ParseStatus = 5
	ParseStatus_PARSE_STATUS_LIMIT_EXCEEDED ParseStatus = 6
	ParseStatus_PARSE_STATUS_AMBIGUOUS      ParseStatus = 7
)

// Enum value maps for ParseStatus.
var (
	ParseStatus_name = map[int32]string{
		0: "PARSE_STATUS_UNSPECIFIED",
		1: "PARSE_STATUS_NOT_APPLICABLE",
		2: "PARSE_STATUS_COMPLETE",
		3: "PARSE_STATUS_PARTIAL",
		4: "PARSE_STATUS_UNSUPPORTED",
		5: "PARSE_STATUS_INVALID",
		6: "PARSE_STATUS_LIMIT_EXCEEDED",
		7: "PARSE_STATUS_AMBIGUOUS",
	}
	ParseStatus_value = map[string]int32{
		"PARSE_STATUS_UNSPECIFIED":    0,
		"PARSE_STATUS_NOT_APPLICABLE": 1,
		"PARSE_STATUS_COMPLETE":       2,
		"PARSE_STATUS_PARTIAL":        3,
		"PARSE_STATUS_UNSUPPORTED":    4,
		"PARSE_STATUS_INVALID":        5,
		"PARSE_STATUS_LIMIT_EXCEEDED": 6,
		"PARSE_STATUS_AMBIGUOUS":      7,
	}
)

func (x ParseStatus) Enum() *ParseStatus {
	p := new(ParseStatus)
	*p = x
	return p
}

func (x ParseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[0].Descriptor()
}

func (ParseStatus) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[0]
}

func (x ParseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParseStatus.Descriptor instead.
func (ParseStatus) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{0}
}

type Dialect int32

const (
	Dialect_DIALECT_UNSPECIFIED Dialect = 0
	Dialect_DIALECT_NONE        Dialect = 1
	Dialect_DIALECT_ARGV        Dialect = 2
	Dialect_DIALECT_POSIX       Dialect = 3
	Dialect_DIALECT_POWERSHELL  Dialect = 4
	Dialect_DIALECT_CMD         Dialect = 5
	Dialect_DIALECT_MIXED       Dialect = 6
)

// Enum value maps for Dialect.
var (
	Dialect_name = map[int32]string{
		0: "DIALECT_UNSPECIFIED",
		1: "DIALECT_NONE",
		2: "DIALECT_ARGV",
		3: "DIALECT_POSIX",
		4: "DIALECT_POWERSHELL",
		5: "DIALECT_CMD",
		6: "DIALECT_MIXED",
	}
	Dialect_value = map[string]int32{
		"DIALECT_UNSPECIFIED": 0,
		"DIALECT_NONE":        1,
		"DIALECT_ARGV":        2,
		"DIALECT_POSIX":       3,
		"DIALECT_POWERSHELL":  4,
		"DIALECT_CMD":         5,
		"DIALECT_MIXED":       6,
	}
)

func (x Dialect) Enum() *Dialect {
	p := new(Dialect)
	*p = x
	return p
}

func (x Dialect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Dialect) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[1].Descriptor()
}

func (Dialect) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[1]
}

func (x Dialect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Dialect.Descriptor instead.
func (Dialect) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{1}
}

type IssueCode int32

const (
	IssueCode_ISSUE_CODE_UNSPECIFIED             IssueCode = 0
	IssueCode_ISSUE_CODE_INVALID_JSON            IssueCode = 1
	IssueCode_ISSUE_CODE_INVALID_UTF8            IssueCode = 2
	IssueCode_ISSUE_CODE_INVALID_SYNTAX          IssueCode = 3
	IssueCode_ISSUE_CODE_DYNAMIC_WORD            IssueCode = 4
	IssueCode_ISSUE_CODE_UNSUPPORTED_CONSTRUCT   IssueCode = 5
	IssueCode_ISSUE_CODE_UNKNOWN_OPERAND_GRAMMAR IssueCode = 6
	IssueCode_ISSUE_CODE_CONFLICTING_SOURCES     IssueCode = 7
	IssueCode_ISSUE_CODE_INPUT_LIMIT             IssueCode = 8
	IssueCode_ISSUE_CODE_NODE_LIMIT              IssueCode = 9
	IssueCode_ISSUE_CODE_DEPTH_LIMIT             IssueCode = 10
	IssueCode_ISSUE_CODE_FACT_LIMIT              IssueCode = 11
	IssueCode_ISSUE_CODE_WRAPPER_LIMIT           IssueCode = 12
	IssueCode_ISSUE_CODE_DUPLICATE_JSON_KEY      IssueCode = 13
	IssueCode_ISSUE_CODE_INTERNAL_PARSER_FAILURE IssueCode = 14
)

// Enum value maps for IssueCode.
var (
	IssueCode_name = map[int32]string{
		0:  "ISSUE_CODE_UNSPECIFIED",
		1:  "ISSUE_CODE_INVALID_JSON",
		2:  "ISSUE_CODE_INVALID_UTF8",
		3:  "ISSUE_CODE_INVALID_SYNTAX",
		4:  "ISSUE_CODE_DYNAMIC_WORD",
		5:  "ISSUE_CODE_UNSUPPORTED_CONSTRUCT",
		6:  "ISSUE_CODE_UNKNOWN_OPERAND_GRAMMAR",
		7:  "ISSUE_CODE_CONFLICTING_SOURCES",
		8:  "ISSUE_CODE_INPUT_LIMIT",
		9:  "ISSUE_CODE_NODE_LIMIT",
		10: "ISSUE_CODE_DEPTH_LIMIT",
		11: "ISSUE_CODE_FACT_LIMIT",
		12: "ISSUE_CODE_WRAPPER_LIMIT",
		13: "ISSUE_CODE_DUPLICATE_JSON_KEY",
		14: "ISSUE_CODE_INTERNAL_PARSER_FAILURE",
	}
	IssueCode_value = map[string]int32{
		"ISSUE_CODE_UNSPECIFIED":             0,
		"ISSUE_CODE_INVALID_JSON":            1,
		"ISSUE_CODE_INVALID_UTF8":            2,
		"ISSUE_CODE_INVALID_SYNTAX":          3,
		"ISSUE_CODE_DYNAMIC_WORD":            4,
		"ISSUE_CODE_UNSUPPORTED_CONSTRUCT":   5,
		"ISSUE_CODE_UNKNOWN_OPERAND_GRAMMAR": 6,
		"ISSUE_CODE_CONFLICTING_SOURCES":     7,
		"ISSUE_CODE_INPUT_LIMIT":             8,
		"ISSUE_CODE_NODE_LIMIT":              9,
		"ISSUE_CODE_DEPTH_LIMIT":             10,
		"ISSUE_CODE_FACT_LIMIT":              11,
		"ISSUE_CODE_WRAPPER_LIMIT":           12,
		"ISSUE_CODE_DUPLICATE_JSON_KEY":      13,
		"ISSUE_CODE_INTERNAL_PARSER_FAILURE": 14,
	}
)

func (x IssueCode) Enum() *IssueCode {
	p := new(IssueCode)
	*p = x
	return p
}

func (x IssueCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IssueCode) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[2].Descriptor()
}

func (IssueCode) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[2]
}

func (x IssueCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IssueCode.Descriptor instead.
func (IssueCode) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{2}
}

type CommandKind int32

const (
	CommandKind_COMMAND_KIND_UNSPECIFIED    CommandKind = 0
	CommandKind_COMMAND_KIND_PROCESS        CommandKind = 1
	CommandKind_COMMAND_KIND_SHELL_REDIRECT CommandKind = 2
)

// Enum value maps for CommandKind.
var (
	CommandKind_name = map[int32]string{
		0: "COMMAND_KIND_UNSPECIFIED",
		1: "COMMAND_KIND_PROCESS",
		2: "COMMAND_KIND_SHELL_REDIRECT",
	}
	CommandKind_value = map[string]int32{
		"COMMAND_KIND_UNSPECIFIED":    0,
		"COMMAND_KIND_PROCESS":        1,
		"COMMAND_KIND_SHELL_REDIRECT": 2,
	}
)

func (x CommandKind) Enum() *CommandKind {
	p := new(CommandKind)
	*p = x
	return p
}

func (x CommandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[3].Descriptor()
}

func (CommandKind) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[3]
}

func (x CommandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandKind.Descriptor instead.
func (CommandKind) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{3}
}

type CommandEffect int32

const (
	CommandEffect_COMMAND_EFFECT_UNSPECIFIED CommandEffect = 0
	CommandEffect_COMMAND_EFFECT_EXECUTE     CommandEffect = 1
	CommandEffect_COMMAND_EFFECT_PREVIEW     CommandEffect = 2
	CommandEffect_COMMAND_EFFECT_UNCERTAIN   CommandEffect = 3
)

// Enum value maps for CommandEffect.
var (
	CommandEffect_name = map[int32]string{
		0: "COMMAND_EFFECT_UNSPECIFIED",
		1: "COMMAND_EFFECT_EXECUTE",
		2: "COMMAND_EFFECT_PREVIEW",
		3: "COMMAND_EFFECT_UNCERTAIN",
	}
	CommandEffect_value = map[string]int32{
		"COMMAND_EFFECT_UNSPECIFIED": 0,
		"COMMAND_EFFECT_EXECUTE":     1,
		"COMMAND_EFFECT_PREVIEW":     2,
		"COMMAND_EFFECT_UNCERTAIN":   3,
	}
)

func (x CommandEffect) Enum() *CommandEffect {
	p := new(CommandEffect)
	*p = x
	return p
}

func (x CommandEffect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandEffect) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[4].Descriptor()
}

func (CommandEffect) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[4]
}

func (x CommandEffect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandEffect.Descriptor instead.
func (CommandEffect) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{4}
}

type QuoteKind int32

const (
	QuoteKind_QUOTE_KIND_UNSPECIFIED QuoteKind = 0
	QuoteKind_QUOTE_KIND_NONE        QuoteKind = 1
	QuoteKind_QUOTE_KIND_SINGLE      QuoteKind = 2
	QuoteKind_QUOTE_KIND_DOUBLE      QuoteKind = 3
	QuoteKind_QUOTE_KIND_MIXED       QuoteKind = 4
)

// Enum value maps for QuoteKind.
var (
	QuoteKind_name = map[int32]string{
		0: "QUOTE_KIND_UNSPECIFIED",
		1: "QUOTE_KIND_NONE",
		2: "QUOTE_KIND_SINGLE",
		3: "QUOTE_KIND_DOUBLE",
		4: "QUOTE_KIND_MIXED",
	}
	QuoteKind_value = map[string]int32{
		"QUOTE_KIND_UNSPECIFIED": 0,
		"QUOTE_KIND_NONE":        1,
		"QUOTE_KIND_SINGLE":      2,
		"QUOTE_KIND_DOUBLE":      3,
		"QUOTE_KIND_MIXED":       4,
	}
)

func (x QuoteKind) Enum() *QuoteKind {
	p := new(QuoteKind)
	*p = x
	return p
}

func (x QuoteKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuoteKind) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[5].Descriptor()
}

func (QuoteKind) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[5]
}

func (x QuoteKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuoteKind.Descriptor instead.
func (QuoteKind) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{5}
}

type OperationKind int32

const (
	OperationKind_OPERATION_KIND_UNSPECIFIED       OperationKind = 0
	OperationKind_OPERATION_KIND_EXECUTE           OperationKind = 1
	OperationKind_OPERATION_KIND_READ              OperationKind = 2
	OperationKind_OPERATION_KIND_WRITE             OperationKind = 3
	OperationKind_OPERATION_KIND_APPEND            OperationKind = 4
	OperationKind_OPERATION_KIND_DELETE            OperationKind = 5
	OperationKind_OPERATION_KIND_COPY              OperationKind = 6
	OperationKind_OPERATION_KIND_MOVE              OperationKind = 7
	OperationKind_OPERATION_KIND_LIST              OperationKind = 8
	OperationKind_OPERATION_KIND_SEARCH            OperationKind = 9
	OperationKind_OPERATION_KIND_FETCH             OperationKind = 10
	OperationKind_OPERATION_KIND_UPLOAD            OperationKind = 11
	OperationKind_OPERATION_KIND_CONNECT           OperationKind = 12
	OperationKind_OPERATION_KIND_LISTEN            OperationKind = 13
	OperationKind_OPERATION_KIND_TUNNEL            OperationKind = 14
	OperationKind_OPERATION_KIND_NETWORK_SCAN      OperationKind = 15
	OperationKind_OPERATION_KIND_DECODE            OperationKind = 16
	OperationKind_OPERATION_KIND_PROCESS_KILL      OperationKind = 17
	OperationKind_OPERATION_KIND_DISK_WRITE        OperationKind = 18
	OperationKind_OPERATION_KIND_PRIVILEGE         OperationKind = 19
	OperationKind_OPERATION_KIND_PERMISSION_CHANGE OperationKind = 20
	OperationKind_OPERATION_KIND_CONFIG_CHANGE     OperationKind = 21
	OperationKind_OPERATION_KIND_ACCOUNT_CHANGE    OperationKind = 22
	OperationKind_OPERATION_KIND_SCHEDULE          OperationKind = 23
	OperationKind_OPERATION_KIND_CONTAINER_RUN     OperationKind = 24
	OperationKind_OPERATION_KIND_WORKLOAD_EXEC     OperationKind = 25
	OperationKind_OPERATION_KIND_NAMESPACE_ENTER   OperationKind = 26
	OperationKind_OPERATION_KIND_ROOT_CHANGE       OperationKind = 27
	OperationKind_OPERATION_KIND_ENVIRONMENT_READ  OperationKind = 28
	OperationKind_OPERATION_KIND_CREDENTIAL_READ   OperationKind = 29
	OperationKind_OPERATION_KIND_POLICY_BYPASS     OperationKind = 30
)

// Enum value maps for OperationKind.
var (
	OperationKind_name = map[int32]string{
		0:  "OPERATION_KIND_UNSPECIFIED",
		1:  "OPERATION_KIND_EXECUTE",
		2:  "OPERATION_KIND_READ",
		3:  "OPERATION_KIND_WRITE",
		4:  "OPERATION_KIND_APPEND",
		5:  "OPERATION_KIND_DELETE",
		6:  "OPERATION_KIND_COPY",
		7:  "OPERATION_KIND_MOVE",
		8:  "OPERATION_KIND_LIST",
		9:  "OPERATION_KIND_SEARCH",
		10: "OPERATION_KIND_FETCH",
		11: "OPERATION_KIND_UPLOAD",
		12: "OPERATION_KIND_CONNECT",
		13: "OPERATION_KIND_LISTEN",
		14: "OPERATION_KIND_TUNNEL",
		15: "OPERATION_KIND_NETWORK_SCAN",
		16: "OPERATION_KIND_DECODE",
		17: "OPERATION_KIND_PROCESS_KILL",
		18: "OPERATION_KIND_DISK_WRITE",
		19: "OPERATION_KIND_PRIVILEGE",
		20: "OPERATION_KIND_PERMISSION_CHANGE",
		21: "OPERATION_KIND_CONFIG_CHANGE",
		22: "OPERATION_KIND_ACCOUNT_CHANGE",
		23: "OPERATION_KIND_SCHEDULE",
		24: "OPERATION_KIND_CONTAINER_RUN",
		25: "OPERATION_KIND_WORKLOAD_EXEC",
		26: "OPERATION_KIND_NAMESPACE_ENTER",
		27: "OPERATION_KIND_ROOT_CHANGE",
		28: "OPERATION_KIND_ENVIRONMENT_READ",
		29: "OPERATION_KIND_CREDENTIAL_READ",
		30: "OPERATION_KIND_POLICY_BYPASS",
	}
	OperationKind_value = map[string]int32{
		"OPERATION_KIND_UNSPECIFIED":       0,
		"OPERATION_KIND_EXECUTE":           1,
		"OPERATION_KIND_READ":              2,
		"OPERATION_KIND_WRITE":             3,
		"OPERATION_KIND_APPEND":            4,
		"OPERATION_KIND_DELETE":            5,
		"OPERATION_KIND_COPY":              6,
		"OPERATION_KIND_MOVE":              7,
		"OPERATION_KIND_LIST":              8,
		"OPERATION_KIND_SEARCH":            9,
		"OPERATION_KIND_FETCH":             10,
		"OPERATION_KIND_UPLOAD":            11,
		"OPERATION_KIND_CONNECT":           12,
		"OPERATION_KIND_LISTEN":            13,
		"OPERATION_KIND_TUNNEL":            14,
		"OPERATION_KIND_NETWORK_SCAN":      15,
		"OPERATION_KIND_DECODE":            16,
		"OPERATION_KIND_PROCESS_KILL":      17,
		"OPERATION_KIND_DISK_WRITE":        18,
		"OPERATION_KIND_PRIVILEGE":         19,
		"OPERATION_KIND_PERMISSION_CHANGE": 20,
		"OPERATION_KIND_CONFIG_CHANGE":     21,
		"OPERATION_KIND_ACCOUNT_CHANGE":    22,
		"OPERATION_KIND_SCHEDULE":          23,
		"OPERATION_KIND_CONTAINER_RUN":     24,
		"OPERATION_KIND_WORKLOAD_EXEC":     25,
		"OPERATION_KIND_NAMESPACE_ENTER":   26,
		"OPERATION_KIND_ROOT_CHANGE":       27,
		"OPERATION_KIND_ENVIRONMENT_READ":  28,
		"OPERATION_KIND_CREDENTIAL_READ":   29,
		"OPERATION_KIND_POLICY_BYPASS":     30,
	}
)

func (x OperationKind) Enum() *OperationKind {
	p := new(OperationKind)
	*p = x
	return p
}

func (x OperationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[6].Descriptor()
}

func (OperationKind) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[6]
}

func (x OperationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationKind.Descriptor instead.
func (OperationKind) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{6}
}

type PathAccess int32

const (
	PathAccess_PATH_ACCESS_UNSPECIFIED PathAccess = 0
	PathAccess_PATH_ACCESS_READ        PathAccess = 1
	PathAccess_PATH_ACCESS_WRITE       PathAccess = 2
	PathAccess_PATH_ACCESS_APPEND      PathAccess = 3
	PathAccess_PATH_ACCESS_DELETE      PathAccess = 4
	PathAccess_PATH_ACCESS_EXECUTE     PathAccess = 5
	PathAccess_PATH_ACCESS_LIST        PathAccess = 6
	PathAccess_PATH_ACCESS_METADATA    PathAccess = 7
	PathAccess_PATH_ACCESS_CONNECT     PathAccess = 8
)

// Enum value maps for PathAccess.
var (
	PathAccess_name = map[int32]string{
		0: "PATH_ACCESS_UNSPECIFIED",
		1: "PATH_ACCESS_READ",
		2: "PATH_ACCESS_WRITE",
		3: "PATH_ACCESS_APPEND",
		4: "PATH_ACCESS_DELETE",
		5: "PATH_ACCESS_EXECUTE",
		6: "PATH_ACCESS_LIST",
		7: "PATH_ACCESS_METADATA",
		8: "PATH_ACCESS_CONNECT",
	}
	PathAccess_value = map[string]int32{
		"PATH_ACCESS_UNSPECIFIED": 0,
		"PATH_ACCESS_READ":        1,
		"PATH_ACCESS_WRITE":       2,
		"PATH_ACCESS_APPEND":      3,
		"PATH_ACCESS_DELETE":      4,
		"PATH_ACCESS_EXECUTE":     5,
		"PATH_ACCESS_LIST":        6,
		"PATH_ACCESS_METADATA":    7,
		"PATH_ACCESS_CONNECT":     8,
	}
)

func (x PathAccess) Enum() *PathAccess {
	p := new(PathAccess)
	*p = x
	return p
}

func (x PathAccess) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathAccess) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[7].Descriptor()
}

func (PathAccess) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[7]
}

func (x PathAccess) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathAccess.Descriptor instead.
func (PathAccess) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{7}
}

type PathFlavor int32

const (
	PathFlavor_PATH_FLAVOR_UNSPECIFIED PathFlavor = 0
	PathFlavor_PATH_FLAVOR_UNKNOWN     PathFlavor = 1
	PathFlavor_PATH_FLAVOR_POSIX       PathFlavor = 2
	PathFlavor_PATH_FLAVOR_WINDOWS     PathFlavor = 3
	PathFlavor_PATH_FLAVOR_DEVICE      PathFlavor = 4
	PathFlavor_PATH_FLAVOR_REGISTRY    PathFlavor = 5
)

// Enum value maps for PathFlavor.
var (
	PathFlavor_name = map[int32]string{
		0: "PATH_FLAVOR_UNSPECIFIED",
		1: "PATH_FLAVOR_UNKNOWN",
		2: "PATH_FLAVOR_POSIX",
		3: "PATH_FLAVOR_WINDOWS",
		4: "PATH_FLAVOR_DEVICE",
		5: "PATH_FLAVOR_REGISTRY",
	}
	PathFlavor_value = map[string]int32{
		"PATH_FLAVOR_UNSPECIFIED": 0,
		"PATH_FLAVOR_UNKNOWN":     1,
		"PATH_FLAVOR_POSIX":       2,
		"PATH_FLAVOR_WINDOWS":     3,
		"PATH_FLAVOR_DEVICE":      4,
		"PATH_FLAVOR_REGISTRY":    5,
	}
)

func (x PathFlavor) Enum() *PathFlavor {
	p := new(PathFlavor)
	*p = x
	return p
}

func (x PathFlavor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathFlavor) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[8].Descriptor()
}

func (PathFlavor) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[8]
}

func (x PathFlavor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathFlavor.Descriptor instead.
func (PathFlavor) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{8}
}

type NetworkScope int32

const (
	NetworkScope_NETWORK_SCOPE_UNSPECIFIED NetworkScope = 0
	NetworkScope_NETWORK_SCOPE_UNKNOWN     NetworkScope = 1
	NetworkScope_NETWORK_SCOPE_LOOPBACK    NetworkScope = 2
	NetworkScope_NETWORK_SCOPE_LINK_LOCAL  NetworkScope = 3
	NetworkScope_NETWORK_SCOPE_PRIVATE     NetworkScope = 4
	NetworkScope_NETWORK_SCOPE_PUBLIC      NetworkScope = 5
)

// Enum value maps for NetworkScope.
var (
	NetworkScope_name = map[int32]string{
		0: "NETWORK_SCOPE_UNSPECIFIED",
		1: "NETWORK_SCOPE_UNKNOWN",
		2: "NETWORK_SCOPE_LOOPBACK",
		3: "NETWORK_SCOPE_LINK_LOCAL",
		4: "NETWORK_SCOPE_PRIVATE",
		5: "NETWORK_SCOPE_PUBLIC",
	}
	NetworkScope_value = map[string]int32{
		"NETWORK_SCOPE_UNSPECIFIED": 0,
		"NETWORK_SCOPE_UNKNOWN":     1,
		"NETWORK_SCOPE_LOOPBACK":    2,
		"NETWORK_SCOPE_LINK_LOCAL":  3,
		"NETWORK_SCOPE_PRIVATE":     4,
		"NETWORK_SCOPE_PUBLIC":      5,
	}
)

func (x NetworkScope) Enum() *NetworkScope {
	p := new(NetworkScope)
	*p = x
	return p
}

func (x NetworkScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkScope) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[9].Descriptor()
}

func (NetworkScope) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[9]
}

func (x NetworkScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkScope.Descriptor instead.
func (NetworkScope) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{9}
}

type NetworkTargetKind int32

const (
	NetworkTargetKind_NETWORK_TARGET_KIND_UNSPECIFIED         NetworkTargetKind = 0
	NetworkTargetKind_NETWORK_TARGET_KIND_UNKNOWN             NetworkTargetKind = 1
	NetworkTargetKind_NETWORK_TARGET_KIND_SINGLE_HOST         NetworkTargetKind = 2
	NetworkTargetKind_NETWORK_TARGET_KIND_SINGLE_ADDRESS_CIDR NetworkTargetKind = 3
	NetworkTargetKind_NETWORK_TARGET_KIND_MULTI_ADDRESS_CIDR  NetworkTargetKind = 4
	NetworkTargetKind_NETWORK_TARGET_KIND_RANGE               NetworkTargetKind = 5
	NetworkTargetKind_NETWORK_TARGET_KIND_LIST                NetworkTargetKind = 6
	NetworkTargetKind_NETWORK_TARGET_KIND_GENERATED           NetworkTargetKind = 7
)

// Enum value maps for NetworkTargetKind.
var (
	NetworkTargetKind_name = map[int32]string{
		0: "NETWORK_TARGET_KIND_UNSPECIFIED",
		1: "NETWORK_TARGET_KIND_UNKNOWN",
		2: "NETWORK_TARGET_KIND_SINGLE_HOST",
		3: "NETWORK_TARGET_KIND_SINGLE_ADDRESS_CIDR",
		4: "NETWORK_TARGET_KIND_MULTI_ADDRESS_CIDR",
		5: "NETWORK_TARGET_KIND_RANGE",
		6: "NETWORK_TARGET_KIND_LIST",
		7: "NETWORK_TARGET_KIND_GENERATED",
	}
	NetworkTargetKind_value = map[string]int32{
		"NETWORK_TARGET_KIND_UNSPECIFIED":         0,
		"NETWORK_TARGET_KIND_UNKNOWN":             1,
		"NETWORK_TARGET_KIND_SINGLE_HOST":         2,
		"NETWORK_TARGET_KIND_SINGLE_ADDRESS_CIDR": 3,
		"NETWORK_TARGET_KIND_MULTI_ADDRESS_CIDR":  4,
		"NETWORK_TARGET_KIND_RANGE":               5,
		"NETWORK_TARGET_KIND_LIST":                6,
		"NETWORK_TARGET_KIND_GENERATED":           7,
	}
)

func (x NetworkTargetKind) Enum() *NetworkTargetKind {
	p := new(NetworkTargetKind)
	*p = x
	return p
}

func (x NetworkTargetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkTargetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[10].Descriptor()
}

func (NetworkTargetKind) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[10]
}

func (x NetworkTargetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkTargetKind.Descriptor instead.
func (NetworkTargetKind) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{10}
}

type NetworkAction int32

const (
	NetworkAction_NETWORK_ACTION_UNSPECIFIED NetworkAction = 0
	NetworkAction_NETWORK_ACTION_CONNECT     NetworkAction = 1
	NetworkAction_NETWORK_ACTION_LISTEN      NetworkAction = 2
	NetworkAction_NETWORK_ACTION_DOWNLOAD    NetworkAction = 3
	NetworkAction_NETWORK_ACTION_UPLOAD      NetworkAction = 4
	NetworkAction_NETWORK_ACTION_DNS         NetworkAction = 5
	NetworkAction_NETWORK_ACTION_TUNNEL      NetworkAction = 6
	NetworkAction_NETWORK_ACTION_SCAN        NetworkAction = 7
)

// Enum value maps for NetworkAction.
var (
	NetworkAction_name = map[int32]string{
		0: "NETWORK_ACTION_UNSPECIFIED",
		1: "NETWORK_ACTION_CONNECT",
		2: "NETWORK_ACTION_LISTEN",
		3: "NETWORK_ACTION_DOWNLOAD",
		4: "NETWORK_ACTION_UPLOAD",
		5: "NETWORK_ACTION_DNS",
		6: "NETWORK_ACTION_TUNNEL",
		7: "NETWORK_ACTION_SCAN",
	}
	NetworkAction_value = map[string]int32{
		"NETWORK_ACTION_UNSPECIFIED": 0,
		"NETWORK_ACTION_CONNECT":     1,
		"NETWORK_ACTION_LISTEN":      2,
		"NETWORK_ACTION_DOWNLOAD":    3,
		"NETWORK_ACTION_UPLOAD":      4,
		"NETWORK_ACTION_DNS":         5,
		"NETWORK_ACTION_TUNNEL":      6,
		"NETWORK_ACTION_SCAN":        7,
	}
)

func (x NetworkAction) Enum() *NetworkAction {
	p := new(NetworkAction)
	*p = x
	return p
}

func (x NetworkAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkAction) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[11].Descriptor()
}

func (NetworkAction) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[11]
}

func (x NetworkAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkAction.Descriptor instead.
func (NetworkAction) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{11}
}

type DataKind int32

const (
	DataKind_DATA_KIND_UNSPECIFIED DataKind = 0
	DataKind_DATA_KIND_STDIN       DataKind = 1
	DataKind_DATA_KIND_STDOUT      DataKind = 2
	DataKind_DATA_KIND_FILE        DataKind = 3
	DataKind_DATA_KIND_NETWORK     DataKind = 4
	DataKind_DATA_KIND_PROCESS     DataKind = 5
)

// Enum value maps for DataKind.
var (
	DataKind_name = map[int32]string{
		0: "DATA_KIND_UNSPECIFIED",
		1: "DATA_KIND_STDIN",
		2: "DATA_KIND_STDOUT",
		3: "DATA_KIND_FILE",
		4: "DATA_KIND_NETWORK",
		5: "DATA_KIND_PROCESS",
	}
	DataKind_value = map[string]int32{
		"DATA_KIND_UNSPECIFIED": 0,
		"DATA_KIND_STDIN":       1,
		"DATA_KIND_STDOUT":      2,
		"DATA_KIND_FILE":        3,
		"DATA_KIND_NETWORK":     4,
		"DATA_KIND_PROCESS":     5,
	}
)

func (x DataKind) Enum() *DataKind {
	p := new(DataKind)
	*p = x
	return p
}

func (x DataKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataKind) Descriptor() protoreflect.EnumDescriptor {
	return file_facts_proto_enumTypes[12].Descriptor()
}

func (DataKind) Type() protoreflect.EnumType {
	return &file_facts_proto_enumTypes[12]
}

func (x DataKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataKind.Descriptor instead.
func (DataKind) EnumDescriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{12}
}

// Facts is the closed, bounded CEL activation for one trusted tool call.
// It is private in-process policy material and must not be logged, audited,
// persisted, or exposed through an API.
type Facts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Cwd           string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	ActiveHome    string                 `protobuf:"bytes,3,opt,name=active_home,json=activeHome,proto3" json:"active_home,omitempty"`
	Parse         *ParseResult           `protobuf:"bytes,4,opt,name=parse,proto3" json:"parse,omitempty"`
	Commands      []*CommandFact         `protobuf:"bytes,5,rep,name=commands,proto3" json:"commands,omitempty"`
	Paths         []*PathFact            `protobuf:"bytes,6,rep,name=paths,proto3" json:"paths,omitempty"`
	Network       []*NetworkFact         `protobuf:"bytes,7,rep,name=network,proto3" json:"network,omitempty"`
	DataFlows     []*DataFlowFact        `protobuf:"bytes,8,rep,name=data_flows,json=dataFlows,proto3" json:"data_flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facts) Reset() {
	*x = Facts{}
	mi := &file_facts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facts) ProtoMessage() {}

func (x *Facts) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facts.ProtoReflect.Descriptor instead.
func (*Facts) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{0}
}

func (x *Facts) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Facts) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Facts) GetActiveHome() string {
	if x != nil {
		return x.ActiveHome
	}
	return ""
}

func (x *Facts) GetParse() *ParseResult {
	if x != nil {
		return x.Parse
	}
	return nil
}

func (x *Facts) GetCommands() []*CommandFact {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Facts) GetPaths() []*PathFact {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Facts) GetNetwork() []*NetworkFact {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Facts) GetDataFlows() []*DataFlowFact {
	if x != nil {
		return x.DataFlows
	}
	return nil
}

type ParseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ParseStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=defenseclaw.guardrail.semantic.v1.ParseStatus" json:"status,omitempty"`
	Dialect       Dialect                `protobuf:"varint,2,opt,name=dialect,proto3,enum=defenseclaw.guardrail.semantic.v1.Dialect" json:"dialect,omitempty"`
	Issues        []IssueCode            `protobuf:"varint,3,rep,packed,name=issues,proto3,enum=defenseclaw.guardrail.semantic.v1.IssueCode" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResult) Reset() {
	*x = ParseResult{}
	mi := &file_facts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResult) ProtoMessage() {}

func (x *ParseResult) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResult.ProtoReflect.Descriptor instead.
func (*ParseResult) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResult) GetStatus() ParseStatus {
	if x != nil {
		return x.Status
	}
	return ParseStatus_PARSE_STATUS_UNSPECIFIED
}

func (x *ParseResult) GetDialect() Dialect {
	if x != nil {
		return x.Dialect
	}
	return Dialect_DIALECT_UNSPECIFIED
}

func (x *ParseResult) GetIssues() []IssueCode {
	if x != nil {
		return x.Issues
	}
	return nil
}

type CommandFact struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentCommandId int64                  `protobuf:"varint,2,opt,name=parent_command_id,json=parentCommandId,proto3" json:"parent_command_id,omitempty"`
	PipelineId      int64                  `protobuf:"varint,3,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Kind            CommandKind            `protobuf:"varint,4,opt,name=kind,proto3,enum=defenseclaw.guardrail.semantic.v1.CommandKind" json:"kind,omitempty"`
	Dialect         Dialect                `protobuf:"varint,5,opt,name=dialect,proto3,enum=defenseclaw.guardrail.semantic.v1.Dialect" json:"dialect,omitempty"`
	Effect          CommandEffect          `protobuf:"varint,6,opt,name=effect,proto3,enum=defenseclaw.guardrail.semantic.v1.CommandEffect" json:"effect,omitempty"`
	Executable      string                 `protobuf:"bytes,7,opt,name=executable,proto3" json:"executable,omitempty"`
	Program         string                 `protobuf:"bytes,8,opt,name=program,proto3" json:"program,omitempty"`
	Argv            []string               `protobuf:"bytes,9,rep,name=argv,proto3" json:"argv,omitempty"`
	Arguments       []*ArgumentFact        `protobuf:"bytes,10,rep,name=arguments,proto3" json:"arguments,omitempty"`
	ArgvComplete    bool                   `protobuf:"varint,11,opt,name=argv_complete,json=argvComplete,proto3" json:"argv_complete,omitempty"`
	Operations      []OperationKind        `protobuf:"varint,12,rep,packed,name=operations,proto3,enum=defenseclaw.guardrail.semantic.v1.OperationKind" json:"operations,omitempty"`
	Redirects       []*RedirectFact        `protobuf:"bytes,13,rep,name=redirects,proto3" json:"redirects,omitempty"`
	Wrappers        []*WrapperFact         `protobuf:"bytes,14,rep,name=wrappers,proto3" json:"wrappers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandFact) Reset() {
	*x = CommandFact{}
	mi := &file_facts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandFact) ProtoMessage() {}

func (x *CommandFact) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandFact.ProtoReflect.Descriptor instead.
func (*CommandFact) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{2}
}

func (x *CommandFact) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommandFact) GetParentCommandId() int64 {
	if x != nil {
		return x.ParentCommandId
	}
	return 0
}

func (x *CommandFact) GetPipelineId() int64 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *CommandFact) GetKind() CommandKind {
	if x != nil {
		return x.Kind
	}
	return CommandKind_COMMAND_KIND_UNSPECIFIED
}

func (x *CommandFact) GetDialect() Dialect {
	if x != nil {
		return x.Dialect
	}
	return Dialect_DIALECT_UNSPECIFIED
}

func (x *CommandFact) GetEffect() CommandEffect {
	if x != nil {
		return x.Effect
	}
	return CommandEffect_COMMAND_EFFECT_UNSPECIFIED
}

func (x *CommandFact) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *CommandFact) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *CommandFact) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *CommandFact) GetArguments() []*ArgumentFact {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CommandFact) GetArgvComplete() bool {
	if x != nil {
		return x.ArgvComplete
	}
	return false
}

func (x *CommandFact) GetOperations() []OperationKind {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *CommandFact) GetRedirects() []*RedirectFact {
	if x != nil {
		return x.Redirects
	}
	return nil
}

func (x *CommandFact) GetWrappers() []*WrapperFact {
	if x != nil {
		return x.Wrappers
	}
	return nil
}

type ArgumentFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Quote         QuoteKind              `protobuf:"varint,2,opt,name=quote,proto3,enum=defenseclaw.guardrail.semantic.v1.QuoteKind" json:"quote,omitempty"`
	Expands       bool                   `protobuf:"varint,3,opt,name=expands,proto3" json:"expands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgumentFact) Reset() {
	*x = ArgumentFact{}
	mi := &file_facts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgumentFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgumentFact) ProtoMessage() {}

func (x *ArgumentFact) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgumentFact.ProtoReflect.Descriptor instead.
func (*ArgumentFact) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{3}
}

func (x *ArgumentFact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ArgumentFact) GetQuote() QuoteKind {
	if x != nil {
		return x.Quote
	}
	return QuoteKind_QUOTE_KIND_UNSPECIFIED
}

func (x *ArgumentFact) GetExpands() bool {
	if x != nil {
		return x.Expands
	}
	return false
}

type RedirectFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int64                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Access        PathAccess             `protobuf:"varint,2,opt,name=access,proto3,enum=defenseclaw.guardrail.semantic.v1.PathAccess" json:"access,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Expands       bool                   `protobuf:"varint,4,opt,name=expands,proto3" json:"expands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectFact) Reset() {
	*x = RedirectFact{}
	mi := &file_facts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectFact) ProtoMessage() {}

func (x *RedirectFact) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectFact.ProtoReflect.Descriptor instead.
func (*RedirectFact) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{4}
}

func (x *RedirectFact) GetFd() int64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *RedirectFact) GetAccess() PathAccess {
	if x != nil {
		return x.Access
	}
	return PathAccess_PATH_ACCESS_UNSPECIFIED
}

func (x *RedirectFact) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RedirectFact) GetExpands() bool {
	if x != nil {
		return x.Expands
	}
	return false
}

type WrapperFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executable    string                 `protobuf:"bytes,1,opt,name=executable,proto3" json:"executable,omitempty"`
	Argv          []string               `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperFact) Reset() {
	*x = WrapperFact{}
	mi := &file_facts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperFact) ProtoMessage() {}

func (x *WrapperFact) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperFact.ProtoReflect.Descriptor instead.
func (*WrapperFact) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{5}
}

func (x *WrapperFact) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *WrapperFact) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

type PathFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     int64                  `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Access        PathAccess             `protobuf:"varint,2,opt,name=access,proto3,enum=defenseclaw.guardrail.semantic.v1.PathAccess" json:"access,omitempty"`
	Flavor        PathFlavor             `protobuf:"varint,3,opt,name=flavor,proto3,enum=defenseclaw.guardrail.semantic.v1.PathFlavor" json:"flavor,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Normalized    string                 `protobuf:"bytes,5,opt,name=normalized,proto3" json:"normalized,omitempty"`
	Absolute      bool                   `protobuf:"varint,6,opt,name=absolute,proto3" json:"absolute,omitempty"`
	Resolved      string                 `protobuf:"bytes,7,opt,name=resolved,proto3" json:"resolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathFact) Reset() {
	*x = PathFact{}
	mi := &file_facts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathFact) ProtoMessage() {}

func (x *PathFact) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathFact.ProtoReflect.Descriptor instead.
func (*PathFact) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{6}
}

func (x *PathFact) GetCommandId() int64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *PathFact) GetAccess() PathAccess {
	if x != nil {
		return x.Access
	}
	return PathAccess_PATH_ACCESS_UNSPECIFIED
}

func (x *PathFact) GetFlavor() PathFlavor {
	if x != nil {
		return x.Flavor
	}
	return PathFlavor_PATH_FLAVOR_UNSPECIFIED
}

func (x *PathFact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PathFact) GetNormalized() string {
	if x != nil {
		return x.Normalized
	}
	return ""
}

func (x *PathFact) GetAbsolute() bool {
	if x != nil {
		return x.Absolute
	}
	return false
}

func (x *PathFact) GetResolved() string {
	if x != nil {
		return x.Resolved
	}
	return ""
}

type NetworkFact struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      int64                  `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action         NetworkAction          `protobuf:"varint,2,opt,name=action,proto3,enum=defenseclaw.guardrail.semantic.v1.NetworkAction" json:"action,omitempty"`
	Scheme         string                 `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Host           string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port           int64                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	NormalizedHost string                 `protobuf:"bytes,6,opt,name=normalized_host,json=normalizedHost,proto3" json:"normalized_host,omitempty"`
	Scope          NetworkScope           `protobuf:"varint,7,opt,name=scope,proto3,enum=defenseclaw.guardrail.semantic.v1.NetworkScope" json:"scope,omitempty"`
	TargetKind     NetworkTargetKind      `protobuf:"varint,8,opt,name=target_kind,json=targetKind,proto3,enum=defenseclaw.guardrail.semantic.v1.NetworkTargetKind" json:"target_kind,omitempty"`
	PrefixLength   int64                  `protobuf:"varint,9,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkFact) Reset() {
	*x = NetworkFact{}
	mi := &file_facts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkFact) ProtoMessage() {}

func (x *NetworkFact) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkFact.ProtoReflect.Descriptor instead.
func (*NetworkFact) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkFact) GetCommandId() int64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *NetworkFact) GetAction() NetworkAction {
	if x != nil {
		return x.Action
	}
	return NetworkAction_NETWORK_ACTION_UNSPECIFIED
}

func (x *NetworkFact) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *NetworkFact) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkFact) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetworkFact) GetNormalizedHost() string {
	if x != nil {
		return x.NormalizedHost
	}
	return ""
}

func (x *NetworkFact) GetScope() NetworkScope {
	if x != nil {
		return x.Scope
	}
	return NetworkScope_NETWORK_SCOPE_UNSPECIFIED
}

func (x *NetworkFact) GetTargetKind() NetworkTargetKind {
	if x != nil {
		return x.TargetKind
	}
	return NetworkTargetKind_NETWORK_TARGET_KIND_UNSPECIFIED
}

func (x *NetworkFact) GetPrefixLength() int64 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

type DataFlowFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCommandId int64                  `protobuf:"varint,1,opt,name=from_command_id,json=fromCommandId,proto3" json:"from_command_id,omitempty"`
	ToCommandId   int64                  `protobuf:"varint,2,opt,name=to_command_id,json=toCommandId,proto3" json:"to_command_id,omitempty"`
	From          DataKind               `protobuf:"varint,3,opt,name=from,proto3,enum=defenseclaw.guardrail.semantic.v1.DataKind" json:"from,omitempty"`
	To            DataKind               `protobuf:"varint,4,opt,name=to,proto3,enum=defenseclaw.guardrail.semantic.v1.DataKind" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFlowFact) Reset() {
	*x = DataFlowFact{}
	mi := &file_facts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFlowFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFlowFact) ProtoMessage() {}

func (x *DataFlowFact) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFlowFact.ProtoReflect.Descriptor instead.
func (*DataFlowFact) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{8}
}

func (x *DataFlowFact) GetFromCommandId() int64 {
	if x != nil {
		return x.FromCommandId
	}
	return 0
}

func (x *DataFlowFact) GetToCommandId() int64 {
	if x != nil {
		return x.ToCommandId
	}
	return 0
}

func (x *DataFlowFact) GetFrom() DataKind {
	if x != nil {
		return x.From
	}
	return DataKind_DATA_KIND_UNSPECIFIED
}

func (x *DataFlowFact) GetTo() DataKind {
	if x != nil {
		return x.To
	}
	return DataKind_DATA_KIND_UNSPECIFIED
}

var File_facts_proto protoreflect.FileDescriptor

const file_facts_proto_rawDesc = "" +
	"\n" +
	"\vfacts.proto\x12!defenseclaw.guardrail.semantic.v1\"\xbd\x03\n" +
	"\x05Facts\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12\x1f\n" +
	"\vactive_home\x18\x03 \x01(\tR\n" +
	"activeHome\x12D\n" +
	"\x05parse\x18\x04 \x01(\v2..defenseclaw.guardrail.semantic.v1.ParseResultR\x05parse\x12J\n" +
	"\bcommands\x18\x05 \x03(\v2..defenseclaw.guardrail.semantic.v1.CommandFactR\bcommands\x12A\n" +
	"\x05paths\x18\x06 \x03(\v2+.defenseclaw.guardrail.semantic.v1.PathFactR\x05paths\x12H\n" +
	"\anetwork\x18\a \x03(\v2..defenseclaw.guardrail.semantic.v1.NetworkFactR\anetwork\x12N\n" +
	"\n" +
	"data_flows\x18\b \x03(\v2/.defenseclaw.guardrail.semantic.v1.DataFlowFactR\tdataFlows\"\xe1\x01\n" +
	"\vParseResult\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..defenseclaw.guardrail.semantic.v1.ParseStatusR\x06status\x12D\n" +
	"\adialect\x18\x02 \x01(\x0e2*.defenseclaw.guardrail.semantic.v1.DialectR\adialect\x12D\n" +
	"\x06issues\x18\x03 \x03(\x0e2,.defenseclaw.guardrail.semantic.v1.IssueCodeR\x06issues\"\xed\x05\n" +
	"\vCommandFact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x11parent_command_id\x18\x02 \x01(\x03R\x0fparentCommandId\x12\x1f\n" +
	"\vpipeline_id\x18\x03 \x01(\x03R\n" +
	"pipelineId\x12B\n" +
	"\x04kind\x18\x04 \x01(\x0e2..defenseclaw.guardrail.semantic.v1.CommandKindR\x04kind\x12D\n" +
	"\adialect\x18\x05 \x01(\x0e2*.defenseclaw.guardrail.semantic.v1.DialectR\adialect\x12H\n" +
	"\x06effect\x18\x06 \x01(\x0e20.defenseclaw.guardrail.semantic.v1.CommandEffectR\x06effect\x12\x1e\n" +
	"\n" +
	"executable\x18\a \x01(\tR\n" +
	"executable\x12\x18\n" +
	"\aprogram\x18\b \x01(\tR\aprogram\x12\x12\n" +
	"\x04argv\x18\t \x03(\tR\x04argv\x12M\n" +
	"\targuments\x18\n" +
	" \x03(\v2/.defenseclaw.guardrail.semantic.v1.ArgumentFactR\targuments\x12#\n" +
	"\rargv_complete\x18\v \x01(\bR\fargvComplete\x12P\n" +
	"\n" +
	"operations\x18\f \x03(\x0e20.defenseclaw.guardrail.semantic.v1.OperationKindR\n" +
	"operations\x12M\n" +
	"\tredirects\x18\r \x03(\v2/.defenseclaw.guardrail.semantic.v1.RedirectFactR\tredirects\x12J\n" +
	"\bwrappers\x18\x0e \x03(\v2..defenseclaw.guardrail.semantic.v1.WrapperFactR\bwrappers\"\x82\x01\n" +
	"\fArgumentFact\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12B\n" +
	"\x05quote\x18\x02 \x01(\x0e2,.defenseclaw.guardrail.semantic.v1.QuoteKindR\x05quote\x12\x18\n" +
	"\aexpands\x18\x03 \x01(\bR\aexpands\"\x97\x01\n" +
	"\fRedirectFact\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x03R\x02fd\x12E\n" +
	"\x06access\x18\x02 \x01(\x0e2-.defenseclaw.guardrail.semantic.v1.PathAccessR\x06access\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x18\n" +
	"\aexpands\x18\x04 \x01(\bR\aexpands\"A\n" +
	"\vWrapperFact\x12\x1e\n" +
	"\n" +
	"executable\x18\x01 \x01(\tR\n" +
	"executable\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\"\xa5\x02\n" +
	"\bPathFact\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x03R\tcommandId\x12E\n" +
	"\x06access\x18\x02 \x01(\x0e2-.defenseclaw.guardrail.semantic.v1.PathAccessR\x06access\x12E\n" +
	"\x06flavor\x18\x03 \x01(\x0e2-.defenseclaw.guardrail.semantic.v1.PathFlavorR\x06flavor\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1e\n" +
	"\n" +
	"normalized\x18\x05 \x01(\tR\n" +
	"normalized\x12\x1a\n" +
	"\babsolute\x18\x06 \x01(\bR\babsolute\x12\x1a\n" +
	"\bresolved\x18\a \x01(\tR\bresolved\"\xa2\x03\n" +
	"\vNetworkFact\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x03R\tcommandId\x12H\n" +
	"\x06action\x18\x02 \x01(\x0e20.defenseclaw.guardrail.semantic.v1.NetworkActionR\x06action\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x03R\x04port\x12'\n" +
	"\x0fnormalized_host\x18\x06 \x01(\tR\x0enormalizedHost\x12E\n" +
	"\x05scope\x18\a \x01(\x0e2/.defenseclaw.guardrail.semantic.v1.NetworkScopeR\x05scope\x12U\n" +
	"\vtarget_kind\x18\b \x01(\x0e24.defenseclaw.guardrail.semantic.v1.NetworkTargetKindR\n" +
	"targetKind\x12#\n" +
	"\rprefix_length\x18\t \x01(\x03R\fprefixLength\"\xd8\x01\n" +
	"\fDataFlowFact\x12&\n" +
	"\x0ffrom_command_id\x18\x01 \x01(\x03R\rfromCommandId\x12\"\n" +
	"\rto_command_id\x18\x02 \x01(\x03R\vtoCommandId\x12?\n" +
	"\x04from\x18\x03 \x01(\x0e2+.defenseclaw.guardrail.semantic.v1.DataKindR\x04from\x12;\n" +
	"\x02to\x18\x04 \x01(\x0e2+.defenseclaw.guardrail.semantic.v1.DataKindR\x02to*\xf6\x01\n" +
	"\vParseStatus\x12\x1c\n" +
	"\x18PARSE_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPARSE_STATUS_NOT_APPLICABLE\x10\x01\x12\x19\n" +
	"\x15PARSE_STATUS_COMPLETE\x10\x02\x12\x18\n" +
	"\x14PARSE_STATUS_PARTIAL\x10\x03\x12\x1c\n" +
	"\x18PARSE_STATUS_UNSUPPORTED\x10\x04\x12\x18\n" +
	"\x14PARSE_STATUS_INVALID\x10\x05\x12\x1f\n" +
	"\x1bPARSE_STATUS_LIMIT_EXCEEDED\x10\x06\x12\x1a\n" +
	"\x16PARSE_STATUS_AMBIGUOUS\x10\a*\x95\x01\n" +
	"\aDialect\x12\x17\n" +
	"\x13DIALECT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDIALECT_NONE\x10\x01\x12\x10\n" +
	"\fDIALECT_ARGV\x10\x02\x12\x11\n" +
	"\rDIALECT_POSIX\x10\x03\x12\x16\n" +
	"\x12DIALECT_POWERSHELL\x10\x04\x12\x0f\n" +
	"\vDIALECT_CMD\x10\x05\x12\x11\n" +
	"\rDIALECT_MIXED\x10\x06*\xe6\x03\n" +
	"\tIssueCode\x12\x1a\n" +
	"\x16ISSUE_CODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ISSUE_CODE_INVALID_JSON\x10\x01\x12\x1b\n" +
	"\x17ISSUE_CODE_INVALID_UTF8\x10\x02\x12\x1d\n" +
	"\x19ISSUE_CODE_INVALID_SYNTAX\x10\x03\x12\x1b\n" +
	"\x17ISSUE_CODE_DYNAMIC_WORD\x10\x04\x12$\n" +
	" ISSUE_CODE_UNSUPPORTED_CONSTRUCT\x10\x05\x12&\n" +
	"\"ISSUE_CODE_UNKNOWN_OPERAND_GRAMMAR\x10\x06\x12\"\n" +
	"\x1eISSUE_CODE_CONFLICTING_SOURCES\x10\a\x12\x1a\n" +
	"\x16ISSUE_CODE_INPUT_LIMIT\x10\b\x12\x19\n" +
	"\x15ISSUE_CODE_NODE_LIMIT\x10\t\x12\x1a\n" +
	"\x16ISSUE_CODE_DEPTH_LIMIT\x10\n" +
	"\x12\x19\n" +
	"\x15ISSUE_CODE_FACT_LIMIT\x10\v\x12\x1c\n" +
	"\x18ISSUE_CODE_WRAPPER_LIMIT\x10\f\x12!\n" +
	"\x1dISSUE_CODE_DUPLICATE_JSON_KEY\x10\r\x12&\n" +
	"\"ISSUE_CODE_INTERNAL_PARSER_FAILURE\x10\x0e*f\n" +
	"\vCommandKind\x12\x1c\n" +
	"\x18COMMAND_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COMMAND_KIND_PROCESS\x10\x01\x12\x1f\n" +
	"\x1bCOMMAND_KIND_SHELL_REDIRECT\x10\x02*\x85\x01\n" +
	"\rCommandEffect\x12\x1e\n" +
	"\x1aCOMMAND_EFFECT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_EFFECT_EXECUTE\x10\x01\x12\x1a\n" +
	"\x16COMMAND_EFFECT_PREVIEW\x10\x02\x12\x1c\n" +
	"\x18COMMAND_EFFECT_UNCERTAIN\x10\x03*\x80\x01\n" +
	"\tQuoteKind\x12\x1a\n" +
	"\x16QUOTE_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fQUOTE_KIND_NONE\x10\x01\x12\x15\n" +
	"\x11QUOTE_KIND_SINGLE\x10\x02\x12\x15\n" +
	"\x11QUOTE_KIND_DOUBLE\x10\x03\x12\x14\n" +
	"\x10QUOTE_KIND_MIXED\x10\x04*\xb6\a\n" +
	"\rOperationKind\x12\x1e\n" +
	"\x1aOPERATION_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16OPERATION_KIND_EXECUTE\x10\x01\x12\x17\n" +
	"\x13OPERATION_KIND_READ\x10\x02\x12\x18\n" +
	"\x14OPERATION_KIND_WRITE\x10\x03\x12\x19\n" +
	"\x15OPERATION_KIND_APPEND\x10\x04\x12\x19\n" +
	"\x15OPERATION_KIND_DELETE\x10\x05\x12\x17\n" +
	"\x13OPERATION_KIND_COPY\x10\x06\x12\x17\n" +
	"\x13OPERATION_KIND_MOVE\x10\a\x12\x17\n" +
	"\x13OPERATION_KIND_LIST\x10\b\x12\x19\n" +
	"\x15OPERATION_KIND_SEARCH\x10\t\x12\x18\n" +
	"\x14OPERATION_KIND_FETCH\x10\n" +
	"\x12\x19\n" +
	"\x15OPERATION_KIND_UPLOAD\x10\v\x12\x1a\n" +
	"\x16OPERATION_KIND_CONNECT\x10\f\x12\x19\n" +
	"\x15OPERATION_KIND_LISTEN\x10\r\x12\x19\n" +
	"\x15OPERATION_KIND_TUNNEL\x10\x0e\x12\x1f\n" +
	"\x1bOPERATION_KIND_NETWORK_SCAN\x10\x0f\x12\x19\n" +
	"\x15OPERATION_KIND_DECODE\x10\x10\x12\x1f\n" +
	"\x1bOPERATION_KIND_PROCESS_KILL\x10\x11\x12\x1d\n" +
	"\x19OPERATION_KIND_DISK_WRITE\x10\x12\x12\x1c\n" +
	"\x18OPERATION_KIND_PRIVILEGE\x10\x13\x12$\n" +
	" OPERATION_KIND_PERMISSION_CHANGE\x10\x14\x12 \n" +
	"\x1cOPERATION_KIND_CONFIG_CHANGE\x10\x15\x12!\n" +
	"\x1dOPERATION_KIND_ACCOUNT_CHANGE\x10\x16\x12\x1b\n" +
	"\x17OPERATION_KIND_SCHEDULE\x10\x17\x12 \n" +
	"\x1cOPERATION_KIND_CONTAINER_RUN\x10\x18\x12 \n" +
	"\x1cOPERATION_KIND_WORKLOAD_EXEC\x10\x19\x12\"\n" +
	"\x1eOPERATION_KIND_NAMESPACE_ENTER\x10\x1a\x12\x1e\n" +
	"\x1aOPERATION_KIND_ROOT_CHANGE\x10\x1b\x12#\n" +
	"\x1fOPERATION_KIND_ENVIRONMENT_READ\x10\x1c\x12\"\n" +
	"\x1eOPERATION_KIND_CREDENTIAL_READ\x10\x1d\x12 \n" +
	"\x1cOPERATION_KIND_POLICY_BYPASS\x10\x1e*\xe8\x01\n" +
	"\n" +
	"PathAccess\x12\x1b\n" +
	"\x17PATH_ACCESS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PATH_ACCESS_READ\x10\x01\x12\x15\n" +
	"\x11PATH_ACCESS_WRITE\x10\x02\x12\x16\n" +
	"\x12PATH_ACCESS_APPEND\x10\x03\x12\x16\n" +
	"\x12PATH_ACCESS_DELETE\x10\x04\x12\x17\n" +
	"\x13PATH_ACCESS_EXECUTE\x10\x05\x12\x14\n" +
	"\x10PATH_ACCESS_LIST\x10\x06\x12\x18\n" +
	"\x14PATH_ACCESS_METADATA\x10\a\x12\x17\n" +
	"\x13PATH_ACCESS_CONNECT\x10\b*\xa4\x01\n" +
	"\n" +
	"PathFlavor\x12\x1b\n" +
	"\x17PATH_FLAVOR_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PATH_FLAVOR_UNKNOWN\x10\x01\x12\x15\n" +
	"\x11PATH_FLAVOR_POSIX\x10\x02\x12\x17\n" +
	"\x13PATH_FLAVOR_WINDOWS\x10\x03\x12\x16\n" +
	"\x12PATH_FLAVOR_DEVICE\x10\x04\x12\x18\n" +
	"\x14PATH_FLAVOR_REGISTRY\x10\x05*\xb7\x01\n" +
	"\fNetworkScope\x12\x1d\n" +
	"\x19NETWORK_SCOPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15NETWORK_SCOPE_UNKNOWN\x10\x01\x12\x1a\n" +
	"\x16NETWORK_SCOPE_LOOPBACK\x10\x02\x12\x1c\n" +
	"\x18NETWORK_SCOPE_LINK_LOCAL\x10\x03\x12\x19\n" +
	"\x15NETWORK_SCOPE_PRIVATE\x10\x04\x12\x18\n" +
	"\x14NETWORK_SCOPE_PUBLIC\x10\x05*\xb7\x02\n" +
	"\x11NetworkTargetKind\x12#\n" +
	"\x1fNETWORK_TARGET_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bNETWORK_TARGET_KIND_UNKNOWN\x10\x01\x12#\n" +
	"\x1fNETWORK_TARGET_KIND_SINGLE_HOST\x10\x02\x12+\n" +
	"'NETWORK_TARGET_KIND_SINGLE_ADDRESS_CIDR\x10\x03\x12*\n" +
	"&NETWORK_TARGET_KIND_MULTI_ADDRESS_CIDR\x10\x04\x12\x1d\n" +
	"\x19NETWORK_TARGET_KIND_RANGE\x10\x05\x12\x1c\n" +
	"\x18NETWORK_TARGET_KIND_LIST\x10\x06\x12!\n" +
	"\x1dNETWORK_TARGET_KIND_GENERATED\x10\a*\xea\x01\n" +
	"\rNetworkAction\x12\x1e\n" +
	"\x1aNETWORK_ACTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16NETWORK_ACTION_CONNECT\x10\x01\x12\x19\n" +
	"\x15NETWORK_ACTION_LISTEN\x10\x02\x12\x1b\n" +
	"\x17NETWORK_ACTION_DOWNLOAD\x10\x03\x12\x19\n" +
	"\x15NETWORK_ACTION_UPLOAD\x10\x04\x12\x16\n" +
	"\x12NETWORK_ACTION_DNS\x10\x05\x12\x19\n" +
	"\x15NETWORK_ACTION_TUNNEL\x10\x06\x12\x17\n" +
	"\x13NETWORK_ACTION_SCAN\x10\a*\x92\x01\n" +
	"\bDataKind\x12\x19\n" +
	"\x15DATA_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDATA_KIND_STDIN\x10\x01\x12\x14\n" +
	"\x10DATA_KIND_STDOUT\x10\x02\x12\x12\n" +
	"\x0eDATA_KIND_FILE\x10\x03\x12\x15\n" +
	"\x11DATA_KIND_NETWORK\x10\x04\x12\x15\n" +
	"\x11DATA_KIND_PROCESS\x10\x05BMZKgithub.com/defenseclaw/defenseclaw/internal/guardrail/semanticpb;semanticpbb\x06proto3"

var (
	file_facts_proto_rawDescOnce sync.Once
	file_facts_proto_rawDescData []byte
)

func file_facts_proto_rawDescGZIP() []byte {
	file_facts_proto_rawDescOnce.Do(func() {
		file_facts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facts_proto_rawDesc), len(file_facts_proto_rawDesc)))
	})
	return file_facts_proto_rawDescData
}

var file_facts_proto_enumTypes = make([]protoimpl.EnumInfo, 13)
var file_facts_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_facts_proto_goTypes = []any{
	(ParseStatus)(0),       // 0: defenseclaw.guardrail.semantic.v1.ParseStatus
	(Dialect)(0),           // 1: defenseclaw.guardrail.semantic.v1.Dialect
	(IssueCode)(0),         // 2: defenseclaw.guardrail.semantic.v1.IssueCode
	(CommandKind)(0),       // 3: defenseclaw.guardrail.semantic.v1.CommandKind
	(CommandEffect)(0),     // 4: defenseclaw.guardrail.semantic.v1.CommandEffect
	(QuoteKind)(0),         // 5: defenseclaw.guardrail.semantic.v1.QuoteKind
	(OperationKind)(0),     // 6: defenseclaw.guardrail.semantic.v1.OperationKind
	(PathAccess)(0),        // 7: defenseclaw.guardrail.semantic.v1.PathAccess
	(PathFlavor)(0),        // 8: defenseclaw.guardrail.semantic.v1.PathFlavor
	(NetworkScope)(0),      // 9: defenseclaw.guardrail.semantic.v1.NetworkScope
	(NetworkTargetKind)(0), // 10: defenseclaw.guardrail.semantic.v1.NetworkTargetKind
	(NetworkAction)(0),     // 11: defenseclaw.guardrail.semantic.v1.NetworkAction
	(DataKind)(0),          // 12: defenseclaw.guardrail.semantic.v1.DataKind
	(*Facts)(nil),          // 13: defenseclaw.guardrail.semantic.v1.Facts
	(*ParseResult)(nil),    // 14: defenseclaw.guardrail.semantic.v1.ParseResult
	(*CommandFact)(nil),    // 15: defenseclaw.guardrail.semantic.v1.CommandFact
	(*ArgumentFact)(nil),   // 16: defenseclaw.guardrail.semantic.v1.ArgumentFact
	(*RedirectFact)(nil),   // 17: defenseclaw.guardrail.semantic.v1.RedirectFact
	(*WrapperFact)(nil),    // 18: defenseclaw.guardrail.semantic.v1.WrapperFact
	(*PathFact)(nil),       // 19: defenseclaw.guardrail.semantic.v1.PathFact
	(*NetworkFact)(nil),    // 20: defenseclaw.guardrail.semantic.v1.NetworkFact
	(*DataFlowFact)(nil),   // 21: defenseclaw.guardrail.semantic.v1.DataFlowFact
}
var file_facts_proto_depIdxs = []int32{
	14, // 0: defenseclaw.guardrail.semantic.v1.Facts.parse:type_name -> defenseclaw.guardrail.semantic.v1.ParseResult
	15, // 1: defenseclaw.guardrail.semantic.v1.Facts.commands:type_name -> defenseclaw.guardrail.semantic.v1.CommandFact
	19, // 2: defenseclaw.guardrail.semantic.v1.Facts.paths:type_name -> defenseclaw.guardrail.semantic.v1.PathFact
	20, // 3: defenseclaw.guardrail.semantic.v1.Facts.network:type_name -> defenseclaw.guardrail.semantic.v1.NetworkFact
	21, // 4: defenseclaw.guardrail.semantic.v1.Facts.data_flows:type_name -> defenseclaw.guardrail.semantic.v1.DataFlowFact
	0,  // 5: defenseclaw.guardrail.semantic.v1.ParseResult.status:type_name -> defenseclaw.guardrail.semantic.v1.ParseStatus
	1,  // 6: defenseclaw.guardrail.semantic.v1.ParseResult.dialect:type_name -> defenseclaw.guardrail.semantic.v1.Dialect
	2,  // 7: defenseclaw.guardrail.semantic.v1.ParseResult.issues:type_name -> defenseclaw.guardrail.semantic.v1.IssueCode
	3,  // 8: defenseclaw.guardrail.semantic.v1.CommandFact.kind:type_name -> defenseclaw.guardrail.semantic.v1.CommandKind
	1,  // 9: defenseclaw.guardrail.semantic.v1.CommandFact.dialect:type_name -> defenseclaw.guardrail.semantic.v1.Dialect
	4,  // 10: defenseclaw.guardrail.semantic.v1.CommandFact.effect:type_name -> defenseclaw.guardrail.semantic.v1.CommandEffect
	16, // 11: defenseclaw.guardrail.semantic.v1.CommandFact.arguments:type_name -> defenseclaw.guardrail.semantic.v1.ArgumentFact
	6,  // 12: defenseclaw.guardrail.semantic.v1.CommandFact.operations:type_name -> defenseclaw.guardrail.semantic.v1.OperationKind
	17, // 13: defenseclaw.guardrail.semantic.v1.CommandFact.redirects:type_name -> defenseclaw.guardrail.semantic.v1.RedirectFact
	18, // 14: defenseclaw.guardrail.semantic.v1.CommandFact.wrappers:type_name -> defenseclaw.guardrail.semantic.v1.WrapperFact
	5,  // 15: defenseclaw.guardrail.semantic.v1.ArgumentFact.quote:type_name -> defenseclaw.guardrail.semantic.v1.QuoteKind
	7,  // 16: defenseclaw.guardrail.semantic.v1.RedirectFact.access:type_name -> defenseclaw.guardrail.semantic.v1.PathAccess
	7,  // 17: defenseclaw.guardrail.semantic.v1.PathFact.access:type_name -> defenseclaw.guardrail.semantic.v1.PathAccess
	8,  // 18: defenseclaw.guardrail.semantic.v1.PathFact.flavor:type_name -> defenseclaw.guardrail.semantic.v1.PathFlavor
	11, // 19: defenseclaw.guardrail.semantic.v1.NetworkFact.action:type_name -> defenseclaw.guardrail.semantic.v1.NetworkAction
	9,  // 20: defenseclaw.guardrail.semantic.v1.NetworkFact.scope:type_name -> defenseclaw.guardrail.semantic.v1.NetworkScope
	10, // 21: defenseclaw.guardrail.semantic.v1.NetworkFact.target_kind:type_name -> defenseclaw.guardrail.semantic.v1.NetworkTargetKind
	12, // 22: defenseclaw.guardrail.semantic.v1.DataFlowFact.from:type_name -> defenseclaw.guardrail.semantic.v1.DataKind
	12, // 23: defenseclaw.guardrail.semantic.v1.DataFlowFact.to:type_name -> defenseclaw.guardrail.semantic.v1.DataKind
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_facts_proto_init() }
func file_facts_proto_init() {
	if File_facts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facts_proto_rawDesc), len(file_facts_proto_rawDesc)),
			NumEnums:      13,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_facts_proto_goTypes,
		DependencyIndexes: file_facts_proto_depIdxs,
		EnumInfos:         file_facts_proto_enumTypes,
		MessageInfos:      file_facts_proto_msgTypes,
	}.Build()
	File_facts_proto = out.File
	file_facts_proto_goTypes = nil
	file_facts_proto_depIdxs = nil
}
