# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

# ruff: noqa: E501

"""Command palette registry for the Textual TUI.

Originally ported from the deleted Go TUI's BuildRegistry; now the
single source of truth for the Textual command palette.
"""

from __future__ import annotations

GO_PARITY_REGISTRY: tuple[tuple[str, str, tuple[str, ...], str, str, bool, str], ...] = (
    ('init', 'defenseclaw', ('init',), 'Initialize DefenseClaw', 'setup', False, ''),
    ('init first-run', 'defenseclaw', ('init', '--non-interactive', '--yes', '--verify'), 'Run guided first-run backend with defaults', 'setup', False, ''),
    ('quickstart', 'defenseclaw', ('quickstart', '--non-interactive', '--yes'), 'Compatibility first-run wrapper', 'setup', False, ''),
    ('setup llm', 'defenseclaw', ('setup', 'llm'), 'Configure the unified LLM interactively', 'setup', False, ''),
    ('setup llm show', 'defenseclaw', ('setup', 'llm', '--show'), 'Show unified LLM settings', 'setup', False, ''),
    ('setup migrate-llm', 'defenseclaw', ('setup', 'migrate-llm'), 'Migrate legacy LLM config into unified llm: block', 'setup', False, ''),
    ('setup skill-scanner', 'defenseclaw', ('setup', 'skill-scanner'), 'Configure skill scanner (interactive)', 'setup', False, ''),
    ('setup mcp-scanner', 'defenseclaw', ('setup', 'mcp-scanner'), 'Configure MCP scanner (interactive)', 'setup', False, ''),
    ('setup openclaw', 'defenseclaw', ('setup', 'openclaw', '--yes'), 'Configure OpenClaw guardrail setup', 'setup', False, ''),
    ('setup zeptoclaw', 'defenseclaw', ('setup', 'zeptoclaw', '--yes'), 'Configure ZeptoClaw guardrail setup', 'setup', False, ''),
    ('setup codex', 'defenseclaw', ('setup', 'codex', '--yes'), 'Configure Codex observability hooks', 'setup', False, ''),
    ('setup claude-code', 'defenseclaw', ('setup', 'claude-code', '--yes'), 'Configure Claude Code observability hooks', 'setup', False, ''),
    ('setup hermes', 'defenseclaw', ('setup', 'hermes', '--yes'), 'Configure Hermes observability hooks', 'setup', False, ''),
    ('setup cursor', 'defenseclaw', ('setup', 'cursor', '--yes'), 'Configure Cursor observability hooks', 'setup', False, ''),
    ('setup windsurf', 'defenseclaw', ('setup', 'windsurf', '--yes'), 'Configure Windsurf observability hooks', 'setup', False, ''),
    ('setup geminicli', 'defenseclaw', ('setup', 'geminicli', '--yes'), 'Configure Gemini CLI observability hooks', 'setup', False, ''),
    ('setup copilot', 'defenseclaw', ('setup', 'copilot', '--yes'), 'Configure Copilot observability hooks', 'setup', False, ''),
    ('setup openhands', 'defenseclaw', ('setup', 'openhands', '--yes'), 'Configure OpenHands observability hooks', 'setup', False, ''),
    ('setup antigravity', 'defenseclaw', ('setup', 'antigravity', '--yes'), 'Configure Antigravity observability hooks', 'setup', False, ''),
    ('setup opencode', 'defenseclaw', ('setup', 'opencode', '--yes'), 'Configure OpenCode observability hooks', 'setup', False, ''),
    ('setup amp', 'defenseclaw', ('setup', 'amp', '--yes'), 'Configure Amp synchronous policy plugin', 'setup', False, ''),
    ('setup omnigent', 'defenseclaw', ('setup', 'omnigent', '--yes'), 'Configure OmniGent ALLOW/ASK/DENY policy bridge', 'setup', False, ''),
    ('setup rotate-token', 'defenseclaw', ('setup', 'rotate-token', '--yes'), 'Rotate gateway and scoped hook tokens', 'setup', False, ''),
    ('setup gateway', 'defenseclaw', ('setup', 'gateway'), 'Configure gateway connection (interactive)', 'setup', False, ''),
    ('setup guardrail', 'defenseclaw', ('setup', 'guardrail'), 'Configure LLM guardrail', 'setup', False, ''),
    ('setup notifications', 'defenseclaw', ('setup', 'notifications'), 'Show/toggle desktop notifications', 'setup', True, '<status|on|off> [--yes]'),
    ('setup splunk', 'defenseclaw', ('setup', 'splunk'), 'Configure Splunk / O11y', 'setup', False, ''),
    ('setup local-observability up', 'defenseclaw', ('setup', 'local-observability', 'up'), 'Start local Prom/Loki/Tempo/Grafana stack', 'setup', False, ''),
    ('setup local-observability down', 'defenseclaw', ('setup', 'local-observability', 'down'), 'Stop local observability stack', 'setup', False, ''),
    ('setup local-observability reset', 'defenseclaw', ('setup', 'local-observability', 'reset', '--yes'), 'Stop local observability and wipe stored event volumes', 'setup', False, ''),
    ('setup local-observability status', 'defenseclaw', ('setup', 'local-observability', 'status'), 'Show local observability stack status', 'setup', False, ''),
    ('setup local-observability url', 'defenseclaw', ('setup', 'local-observability', 'url'), 'Show local observability URLs', 'setup', False, ''),
    ('setup local-observability logs', 'defenseclaw', ('setup', 'local-observability', 'logs'), 'Tail local observability logs', 'setup', False, ''),
    ('setup observability add', 'defenseclaw', ('setup', 'observability', 'add'), 'Add an observability/audit destination preset', 'setup', True, '<preset> [flags]'),
    ('setup observability list', 'defenseclaw', ('setup', 'observability', 'list'), 'List configured observability destinations', 'setup', False, ''),
    ('setup observability enable', 'defenseclaw', ('setup', 'observability', 'enable'), 'Enable an observability destination', 'setup', True, '<name>'),
    ('setup observability disable', 'defenseclaw', ('setup', 'observability', 'disable'), 'Disable an observability destination', 'setup', True, '<name>'),
    ('setup observability remove', 'defenseclaw', ('setup', 'observability', 'remove', '--yes'), 'Remove an observability destination', 'setup', True, '<name>'),
    ('setup observability test', 'defenseclaw', ('setup', 'observability', 'test'), 'Probe an observability destination', 'setup', True, '<name>'),
    ('setup galileo', 'defenseclaw', ('setup', 'galileo'), 'Configure Galileo Cloud or self-hosted OTLP traces', 'setup', False, ''),
    ('setup galileo status', 'defenseclaw', ('setup', 'galileo', 'status'), 'Show Galileo destination status', 'info', False, ''),
    ('setup galileo test', 'defenseclaw', ('setup', 'galileo', 'test'), 'Send a Galileo OTLP canary trace', 'scan', False, ''),
    ('setup webhook add', 'defenseclaw', ('setup', 'webhook', 'add'), 'Add a notifier webhook', 'setup', True, '<name> --type <slack|teams|pagerduty|generic>'),
    ('setup webhook list', 'defenseclaw', ('setup', 'webhook', 'list'), 'List notifier webhooks', 'setup', False, ''),
    ('setup webhook show', 'defenseclaw', ('setup', 'webhook', 'show'), 'Show a notifier webhook', 'setup', True, '<name>'),
    ('setup webhook enable', 'defenseclaw', ('setup', 'webhook', 'enable'), 'Enable a notifier webhook', 'setup', True, '<name>'),
    ('setup webhook disable', 'defenseclaw', ('setup', 'webhook', 'disable'), 'Disable a notifier webhook', 'setup', True, '<name>'),
    ('setup webhook remove', 'defenseclaw', ('setup', 'webhook', 'remove', '--yes'), 'Remove a notifier webhook', 'setup', True, '<name>'),
    ('setup webhook test', 'defenseclaw', ('setup', 'webhook', 'test'), 'Send/probe a notifier webhook', 'setup', True, '<name>'),
    ('setup provider add', 'defenseclaw', ('setup', 'provider', 'add'), 'Add a custom LLM provider to the overlay', 'setup', False, ''),
    ('setup provider remove', 'defenseclaw', ('setup', 'provider', 'remove'), 'Remove a custom LLM provider from the overlay', 'setup', False, ''),
    ('setup provider list', 'defenseclaw', ('setup', 'provider', 'list'), 'List overlay provider entries', 'setup', False, ''),
    ('setup provider show', 'defenseclaw', ('setup', 'provider', 'show'), 'Show merged provider registry', 'setup', False, ''),
    ('agent discover', 'defenseclaw', ('agent', 'discover'), 'Discover installed agents and emit sanitized telemetry', 'info', False, ''),
    ('agent usage', 'defenseclaw', ('agent', 'usage'), 'Show continuous AI visibility from the sidecar', 'info', False, ''),
    ('agent usage --refresh', 'defenseclaw', ('agent', 'usage', '--refresh'), 'Trigger an AI-usage scan and render results', 'scan', False, ''),
    ('agent discovery setup', 'defenseclaw', ('agent', 'discovery', 'setup'), 'Interactive AI discovery wizard (mode, intervals, sources)', 'setup', False, ''),
    ('agent discovery enable', 'defenseclaw', ('agent', 'discovery', 'enable', '--yes'), 'Enable AI discovery, save config, restart, and scan', 'setup', False, ''),
    ('agent discovery disable', 'defenseclaw', ('agent', 'discovery', 'disable', '--yes'), 'Disable AI discovery and restart the gateway', 'setup', False, ''),
    ('agent discovery status', 'defenseclaw', ('agent', 'discovery', 'status'), 'Show on-disk vs live AI discovery state', 'info', False, ''),
    ('agent discovery scan', 'defenseclaw', ('agent', 'discovery', 'scan'), 'Trigger one immediate AI discovery scan', 'scan', False, ''),
    ('agent signatures list', 'defenseclaw', ('agent', 'signatures', 'list'), 'List the merged AI discovery signature catalog', 'info', False, ''),
    ('scan skill', 'defenseclaw', ('skill', 'scan'), 'Scan a skill', 'scan', True, '<skill-name>'),
    ('scan skill --all', 'defenseclaw', ('skill', 'scan', '--all'), 'Scan all skills', 'scan', False, ''),
    ('scan mcp', 'defenseclaw', ('mcp', 'scan'), 'Scan an MCP server', 'scan', True, '<url>'),
    ('scan mcp --all', 'defenseclaw', ('mcp', 'scan', '--all'), 'Scan all MCP servers', 'scan', False, ''),
    ('scan plugin', 'defenseclaw', ('plugin', 'scan'), 'Scan a plugin', 'scan', True, '<plugin-name>'),
    ('scan aibom', 'defenseclaw', ('aibom', 'scan'), 'Generate AIBOM inventory', 'scan', False, ''),
    ('scan code', 'defenseclaw-gateway', ('scan', 'code'), 'CodeGuard scan', 'scan', True, '<path>'),
    ('block skill', 'defenseclaw', ('skill', 'block'), 'Block a skill', 'enforce', True, '<skill-name>'),
    ('allow skill', 'defenseclaw', ('skill', 'allow'), 'Allow-list a skill', 'enforce', True, '<skill-name>'),
    ('unblock skill', 'defenseclaw', ('skill', 'unblock'), 'Unblock a skill', 'enforce', True, '<skill-name>'),
    ('disable skill', 'defenseclaw', ('skill', 'disable'), 'Disable a skill at runtime', 'enforce', True, '<skill-name>'),
    ('enable skill', 'defenseclaw', ('skill', 'enable'), 'Enable a skill at runtime', 'enforce', True, '<skill-name>'),
    ('quarantine skill', 'defenseclaw', ('skill', 'quarantine'), 'Quarantine a skill', 'enforce', True, '<skill-name>'),
    ('restore skill', 'defenseclaw', ('skill', 'restore'), 'Restore a quarantined skill', 'enforce', True, '<skill-name>'),
    ('block mcp', 'defenseclaw', ('mcp', 'block'), 'Block an MCP server', 'enforce', True, '<url>'),
    ('allow mcp', 'defenseclaw', ('mcp', 'allow'), 'Allow-list an MCP server', 'enforce', True, '<url>'),
    ('unblock mcp', 'defenseclaw', ('mcp', 'unblock'), 'Unblock an MCP server', 'enforce', True, '<url>'),
    ('set mcp', 'defenseclaw', ('mcp', 'set'), "Scan + set MCP server in the active connector's config", 'enforce', True, '<url>'),
    ('unset mcp', 'defenseclaw', ('mcp', 'unset'), "Unset MCP server from the active connector's config", 'enforce', True, '<url>'),
    ('block plugin', 'defenseclaw', ('plugin', 'block'), 'Block a plugin', 'enforce', True, '<plugin-name>'),
    ('allow plugin', 'defenseclaw', ('plugin', 'allow'), 'Allow-list a plugin', 'enforce', True, '<plugin-name>'),
    ('disable plugin', 'defenseclaw', ('plugin', 'disable'), 'Disable a plugin at runtime', 'enforce', True, '<plugin-name>'),
    ('enable plugin', 'defenseclaw', ('plugin', 'enable'), 'Enable a plugin at runtime', 'enforce', True, '<plugin-name>'),
    ('quarantine plugin', 'defenseclaw', ('plugin', 'quarantine'), 'Quarantine a plugin', 'enforce', True, '<plugin-name>'),
    ('restore plugin', 'defenseclaw', ('plugin', 'restore'), 'Restore a quarantined plugin', 'enforce', True, '<plugin-name>'),
    ('remove plugin', 'defenseclaw', ('plugin', 'remove'), 'Remove a plugin', 'enforce', True, '<plugin-name>'),
    ('block tool', 'defenseclaw', ('tool', 'block'), 'Block a tool', 'enforce', True, '<tool-name>'),
    ('allow tool', 'defenseclaw', ('tool', 'allow'), 'Allow-list a tool', 'enforce', True, '<tool-name>'),
    ('unblock tool', 'defenseclaw', ('tool', 'unblock'), 'Unblock a tool', 'enforce', True, '<tool-name>'),
    ('install skill', 'defenseclaw', ('skill', 'install'), 'Install a skill from ClawHub', 'install', True, '<skill-name>'),
    ('install plugin', 'defenseclaw', ('plugin', 'install'), 'Install a plugin', 'install', True, '<plugin-name>'),
    ('install codeguard', 'defenseclaw', ('codeguard', 'install-skill'), 'Install CodeGuard skill', 'install', False, ''),
    ('policy list', 'defenseclaw', ('policy', 'list'), 'List policies', 'policy', False, ''),
    ('policy show', 'defenseclaw', ('policy', 'show'), 'Show policy details', 'policy', True, '<policy-name>'),
    ('policy create', 'defenseclaw', ('policy', 'create'), 'Create a new policy', 'policy', True, '<policy-name>'),
    ('policy activate', 'defenseclaw', ('policy', 'activate'), 'Activate a policy', 'policy', True, '<policy-name>'),
    ('policy delete', 'defenseclaw', ('policy', 'delete'), 'Delete a user policy', 'policy', True, '<policy-name>'),
    ('policy validate', 'defenseclaw', ('policy', 'validate'), 'Validate policy data + Rego', 'policy', False, ''),
    ('policy test', 'defenseclaw', ('policy', 'test'), 'Run OPA policy tests', 'policy', False, ''),
    ('policy edit actions', 'defenseclaw', ('policy', 'edit', 'actions'), 'Edit severity action rules', 'policy', False, ''),
    ('policy edit scanner', 'defenseclaw', ('policy', 'edit', 'scanner'), 'Edit scanner overrides', 'policy', False, ''),
    ('policy edit guardrail', 'defenseclaw', ('policy', 'edit', 'guardrail'), 'Edit guardrail policy', 'policy', False, ''),
    ('policy edit firewall', 'defenseclaw', ('policy', 'edit', 'firewall'), 'Edit firewall policy', 'policy', False, ''),
    ('policy evaluate', 'defenseclaw-gateway', ('policy', 'evaluate'), 'Dry-run admission evaluation', 'policy', False, ''),
    ('policy evaluate-firewall', 'defenseclaw-gateway', ('policy', 'evaluate-firewall'), 'Dry-run firewall evaluation', 'policy', False, ''),
    ('policy reload', 'defenseclaw-gateway', ('policy', 'reload'), 'Reload policy in running sidecar', 'policy', False, ''),
    ('policy domains', 'defenseclaw-gateway', ('policy', 'domains'), 'Show firewall domain lists', 'policy', False, ''),
    ('list skills', 'defenseclaw', ('skill', 'list'), 'List skills with scan status', 'info', False, ''),
    ('list mcps', 'defenseclaw', ('mcp', 'list'), 'List MCP servers with status', 'info', False, ''),
    ('list plugins', 'defenseclaw', ('plugin', 'list'), 'List installed plugins', 'info', False, ''),
    ('list tools', 'defenseclaw', ('tool', 'list'), 'List tool rules', 'info', False, ''),
    ('info skill', 'defenseclaw', ('skill', 'info'), 'Show skill details', 'info', True, '<skill-name>'),
    ('info plugin', 'defenseclaw', ('plugin', 'info'), 'Show plugin details', 'info', True, '<plugin-name>'),
    ('tool status', 'defenseclaw', ('tool', 'status'), 'Show tool block/allow status', 'info', True, '<tool-name>'),
    ('status', 'defenseclaw', ('status',), 'Show DefenseClaw status', 'info', False, ''),
    ('doctor', 'defenseclaw', ('doctor',), 'Run health checks', 'info', False, ''),
    ('doctor run', 'defenseclaw', ('doctor',), 'Run health checks', 'info', False, ''),
    ('doctor --fix', 'defenseclaw', ('doctor', '--fix', '--yes'), 'Auto-repair safe health issues', 'info', False, ''),
    ('config validate', 'defenseclaw', ('config', 'validate'), 'Validate config.yaml', 'info', False, ''),
    ('config show', 'defenseclaw', ('config', 'show'), 'Show resolved config with secrets masked', 'info', False, ''),
    ('config show effective observability', 'defenseclaw', ('config', 'show', '--effective', '--section', 'observability'), 'Show effective observability policy', 'info', False, ''),
    ('config reference observability', 'defenseclaw', ('config', 'reference', 'observability'), 'Show the complete observability reference', 'info', False, ''),
    ('observability plan', 'defenseclaw', ('observability', 'plan'), 'Show collection and destination routing plan', 'info', False, ''),
    ('config path', 'defenseclaw', ('config', 'path'), 'Show DefenseClaw filesystem paths', 'info', False, ''),
    ('keys list', 'defenseclaw', ('keys', 'list'), 'List configured and missing credentials', 'info', False, ''),
    ('keys list --json', 'defenseclaw', ('keys', 'list', '--json'), 'List credentials as JSON for setup parity', 'info', False, ''),
    ('keys check', 'defenseclaw', ('keys', 'check'), 'Fail if required credentials are missing', 'info', False, ''),
    ('keys set', 'defenseclaw', ('keys', 'set'), 'Persist a credential to the DefenseClaw .env', 'setup', True, '<ENV_NAME>'),
    ('keys fill-missing', 'defenseclaw', ('keys', 'fill-missing', '--yes'), 'List missing required credentials', 'setup', False, ''),
    ('settings save', 'defenseclaw', ('settings', 'save'), 'Persist current settings/config', 'setup', False, ''),
    ('guardrail status', 'defenseclaw', ('guardrail', 'status'), 'Show guardrail status', 'info', False, ''),
    ('guardrail enable', 'defenseclaw', ('guardrail', 'enable', '--yes'), 'Enable guardrail', 'setup', False, ''),
    ('guardrail disable', 'defenseclaw', ('guardrail', 'disable', '--yes'), 'Disable guardrail', 'setup', False, ''),
    ('version', 'defenseclaw', ('version',), 'Show DefenseClaw version information', 'info', False, ''),
    ('start', 'defenseclaw-gateway', ('start',), 'Start gateway sidecar', 'daemon', False, ''),
    ('stop', 'defenseclaw-gateway', ('stop',), 'Stop gateway sidecar', 'daemon', False, ''),
    ('restart', 'defenseclaw-gateway', ('restart',), 'Restart gateway sidecar', 'daemon', False, ''),
    ('gateway status', 'defenseclaw-gateway', ('status',), 'Show gateway health', 'daemon', False, ''),
    ('watchdog start', 'defenseclaw-gateway', ('watchdog', 'start'), 'Start health watchdog', 'daemon', False, ''),
    ('watchdog stop', 'defenseclaw-gateway', ('watchdog', 'stop'), 'Stop health watchdog', 'daemon', False, ''),
    ('watchdog status', 'defenseclaw-gateway', ('watchdog', 'status'), 'Show watchdog status', 'daemon', False, ''),
    ('connector verify', 'defenseclaw-gateway', ('connector', 'verify'), 'Verify connector config is clean/current', 'daemon', False, ''),
    ('connector teardown', 'defenseclaw-gateway', ('connector', 'teardown'), 'Remove active connector config patches', 'daemon', False, ''),
    ('connector list-backups', 'defenseclaw-gateway', ('connector', 'list-backups'), 'List connector backup files', 'daemon', False, ''),
    ('gateway audit export', 'defenseclaw-gateway', ('audit', 'export'), 'Export gateway audit log', 'info', False, ''),
    ('gateway provenance show', 'defenseclaw-gateway', ('provenance', 'show'), 'Show gateway binary/config provenance', 'info', False, ''),
    ('sandbox init', 'defenseclaw', ('sandbox', 'init'), 'Initialize sandbox environment', 'sandbox', False, ''),
    ('sandbox setup', 'defenseclaw', ('sandbox', 'setup'), 'Configure sandbox networking', 'sandbox', False, ''),
    ('sandbox start', 'defenseclaw-gateway', ('sandbox', 'start'), 'Start sandbox services', 'sandbox', False, ''),
    ('sandbox stop', 'defenseclaw-gateway', ('sandbox', 'stop'), 'Stop sandbox services', 'sandbox', False, ''),
    ('sandbox restart', 'defenseclaw-gateway', ('sandbox', 'restart'), 'Restart sandbox services', 'sandbox', False, ''),
    ('sandbox status', 'defenseclaw-gateway', ('sandbox', 'status'), 'Show sandbox status', 'sandbox', False, ''),
    ('sandbox exec', 'defenseclaw-gateway', ('sandbox', 'exec'), 'Run command in sandbox', 'sandbox', True, '<command>'),
    ('sandbox shell', 'defenseclaw-gateway', ('sandbox', 'shell'), 'Open sandbox shell', 'sandbox', False, ''),
    ('sandbox policy diff', 'defenseclaw-gateway', ('sandbox', 'policy', 'diff'), 'Compare policy vs endpoints', 'sandbox', False, ''),
    ('upgrade', 'defenseclaw', ('upgrade', '--yes'), 'Upgrade DefenseClaw', 'other', False, ''),
    ('uninstall dry-run', 'defenseclaw', ('uninstall', '--dry-run'), 'Preview uninstall changes without modifying the system', 'other', False, ''),
    ('uninstall --yes', 'defenseclaw', ('uninstall', '--yes'), 'Uninstall DefenseClaw after showing the plan', 'other', False, ''),
    ('uninstall --all --yes', 'defenseclaw', ('uninstall', '--all', '--yes'), 'Uninstall DefenseClaw and wipe local data', 'other', False, ''),
    ('reset --yes', 'defenseclaw', ('reset', '--yes'), 'Wipe DefenseClaw local data and keep binaries', 'other', False, ''),
    ('setup', 'defenseclaw', ('setup',), 'Show setup command help', 'setup', False, ''),
    ('setup local-observability', 'defenseclaw', ('setup', 'local-observability'), 'Show local observability commands', 'setup', False, ''),
    ('setup observability', 'defenseclaw', ('setup', 'observability'), 'Show observability sink commands', 'setup', False, ''),
    ('setup provider', 'defenseclaw', ('setup', 'provider'), 'Show provider registry commands', 'setup', False, ''),
    ('setup webhook', 'defenseclaw', ('setup', 'webhook'), 'Show webhook commands', 'setup', False, ''),
    ('skill', 'defenseclaw', ('skill',), 'Show skill commands', 'info', False, ''),
    ('skill list', 'defenseclaw', ('skill', 'list'), 'List skills with scan status', 'info', False, ''),
    ('skill search', 'defenseclaw', ('skill', 'search'), 'Search available skills', 'info', True, '<query>'),
    ('skill scan', 'defenseclaw', ('skill', 'scan'), 'Scan a skill', 'scan', True, '<skill-name>'),
    ('skill info', 'defenseclaw', ('skill', 'info'), 'Show skill details', 'info', True, '<skill-name>'),
    ('skill allow', 'defenseclaw', ('skill', 'allow'), 'Allow-list a skill', 'enforce', True, '<skill-name>'),
    ('skill block', 'defenseclaw', ('skill', 'block'), 'Block a skill', 'enforce', True, '<skill-name>'),
    ('skill disable', 'defenseclaw', ('skill', 'disable'), 'Disable a skill at runtime', 'enforce', True, '<skill-name>'),
    ('skill enable', 'defenseclaw', ('skill', 'enable'), 'Enable a skill at runtime', 'enforce', True, '<skill-name>'),
    ('skill install', 'defenseclaw', ('skill', 'install'), 'Install a skill from ClawHub', 'install', True, '<skill-name>'),
    ('skill quarantine', 'defenseclaw', ('skill', 'quarantine'), 'Quarantine a skill', 'enforce', True, '<skill-name>'),
    ('skill restore', 'defenseclaw', ('skill', 'restore'), 'Restore a quarantined skill', 'enforce', True, '<skill-name>'),
    ('skill unblock', 'defenseclaw', ('skill', 'unblock'), 'Unblock a skill', 'enforce', True, '<skill-name>'),
    ('mcp', 'defenseclaw', ('mcp',), 'Show MCP commands', 'info', False, ''),
    ('mcp list', 'defenseclaw', ('mcp', 'list'), 'List MCP servers with status', 'info', False, ''),
    ('mcp scan', 'defenseclaw', ('mcp', 'scan'), 'Scan an MCP server', 'scan', True, '<url>'),
    ('mcp allow', 'defenseclaw', ('mcp', 'allow'), 'Allow-list an MCP server', 'enforce', True, '<url>'),
    ('mcp block', 'defenseclaw', ('mcp', 'block'), 'Block an MCP server', 'enforce', True, '<url>'),
    ('mcp set', 'defenseclaw', ('mcp', 'set'), "Scan + set MCP server in the active connector's config", 'enforce', True, '<name> [--url <url>]'),
    ('mcp unblock', 'defenseclaw', ('mcp', 'unblock'), 'Unblock an MCP server', 'enforce', True, '<url>'),
    ('mcp unset', 'defenseclaw', ('mcp', 'unset'), "Unset MCP server from the active connector's config", 'enforce', True, '<name-or-url>'),
    ('plugin', 'defenseclaw', ('plugin',), 'Show plugin commands', 'info', False, ''),
    ('plugin list', 'defenseclaw', ('plugin', 'list'), 'List installed plugins', 'info', False, ''),
    ('plugin scan', 'defenseclaw', ('plugin', 'scan'), 'Scan a plugin', 'scan', True, '<plugin-name>'),
    ('plugin info', 'defenseclaw', ('plugin', 'info'), 'Show plugin details', 'info', True, '<plugin-name>'),
    ('plugin allow', 'defenseclaw', ('plugin', 'allow'), 'Allow-list a plugin', 'enforce', True, '<plugin-name>'),
    ('plugin block', 'defenseclaw', ('plugin', 'block'), 'Block a plugin', 'enforce', True, '<plugin-name>'),
    ('plugin disable', 'defenseclaw', ('plugin', 'disable'), 'Disable a plugin at runtime', 'enforce', True, '<plugin-name>'),
    ('plugin enable', 'defenseclaw', ('plugin', 'enable'), 'Enable a plugin at runtime', 'enforce', True, '<plugin-name>'),
    ('plugin install', 'defenseclaw', ('plugin', 'install'), 'Install a plugin', 'install', True, '<plugin-name>'),
    ('plugin quarantine', 'defenseclaw', ('plugin', 'quarantine'), 'Quarantine a plugin', 'enforce', True, '<plugin-name>'),
    ('plugin remove', 'defenseclaw', ('plugin', 'remove'), 'Remove a plugin', 'enforce', True, '<plugin-name>'),
    ('plugin restore', 'defenseclaw', ('plugin', 'restore'), 'Restore a quarantined plugin', 'enforce', True, '<plugin-name>'),
    ('tool', 'defenseclaw', ('tool',), 'Show tool commands', 'info', False, ''),
    ('tool list', 'defenseclaw', ('tool', 'list'), 'List tool rules', 'info', False, ''),
    ('tool allow', 'defenseclaw', ('tool', 'allow'), 'Allow-list a tool', 'enforce', True, '<tool-name>'),
    ('tool block', 'defenseclaw', ('tool', 'block'), 'Block a tool', 'enforce', True, '<tool-name>'),
    ('tool unblock', 'defenseclaw', ('tool', 'unblock'), 'Unblock a tool', 'enforce', True, '<tool-name>'),
    ('policy', 'defenseclaw', ('policy',), 'Show policy commands', 'policy', False, ''),
    ('policy edit', 'defenseclaw', ('policy', 'edit'), 'Show policy edit commands', 'policy', False, ''),
    ('keys', 'defenseclaw', ('keys',), 'Show credential commands', 'info', False, ''),
    ('config', 'defenseclaw', ('config',), 'Show config commands', 'info', False, ''),
    ('guardrail', 'defenseclaw', ('guardrail',), 'Show guardrail commands', 'info', False, ''),
    ('settings', 'defenseclaw', ('settings',), 'Show settings commands', 'setup', False, ''),
    ('audit', 'defenseclaw', ('audit',), 'Show audit commands', 'info', False, ''),
    ('codeguard', 'defenseclaw', ('codeguard',), 'Show CodeGuard commands', 'install', False, ''),
    ('codeguard install-skill', 'defenseclaw', ('codeguard', 'install-skill'), 'Install CodeGuard skill', 'install', False, ''),
    ('aibom', 'defenseclaw', ('aibom',), 'Show AIBOM commands', 'scan', False, ''),
    ('sandbox', 'defenseclaw', ('sandbox',), 'Show sandbox commands', 'sandbox', False, ''),
    ('reset', 'defenseclaw', ('reset',), 'Run interactive local data reset', 'other', False, ''),
    ('uninstall', 'defenseclaw', ('uninstall',), 'Run interactive uninstall flow', 'other', False, ''),
    ('skills', 'defenseclaw', ('skill', 'list'), 'List skills', 'info', False, ''),
    ('mcps', 'defenseclaw', ('mcp', 'list'), 'List MCP servers', 'info', False, ''),
    ('plugins', 'defenseclaw', ('plugin', 'list'), 'List plugins', 'info', False, ''),
    ('tools', 'defenseclaw', ('tool', 'list'), 'List tools', 'info', False, ''),
    ('alerts', 'defenseclaw', ('alerts', '--no-tui'), 'List alerts', 'info', False, ''),
    ('alerts acknowledge', 'defenseclaw', ('alerts', 'acknowledge'), 'Acknowledge alerts by severity', 'enforce', True, '--severity HIGH'),
    ('alerts dismiss', 'defenseclaw', ('alerts', 'dismiss'), 'Dismiss alerts by severity', 'enforce', True, '--severity HIGH'),
    ('audit log-activity', 'defenseclaw', ('audit', 'log-activity'), 'Log operator activity (payload via --payload-file)', 'other', True, '--payload-file <path>'),
    ('fix credentials', 'defenseclaw', ('keys', 'fill-missing', '--yes'), 'List missing required credentials', 'setup', False, ''),
    ('setup connector', 'defenseclaw', ('setup',), 'Open connector setup choices in the CLI', 'setup', False, ''),
    ('restart gateway', 'defenseclaw-gateway', ('restart',), 'Restart the gateway sidecar', 'daemon', False, ''),
    ('open setup', 'defenseclaw', ('setup',), 'Jump to the TUI Setup panel', 'info', False, ''),
    ('readiness', 'defenseclaw', ('doctor',), 'Run health checks that feed Setup Readiness', 'info', False, ''),
    ('help', 'defenseclaw', ('--help',), 'Show CLI help', 'info', False, ''),
)
