// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: secureclient.proto

package defenseclawv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DefenseClawSecureClientService_GetHealth_FullMethodName          = "/defenseclaw.secureclient.v1.DefenseClawSecureClientService/GetHealth"
	DefenseClawSecureClientService_GetStatsSnapshot_FullMethodName   = "/defenseclaw.secureclient.v1.DefenseClawSecureClientService/GetStatsSnapshot"
	DefenseClawSecureClientService_WatchNotifications_FullMethodName = "/defenseclaw.secureclient.v1.DefenseClawSecureClientService/WatchNotifications"
)

// DefenseClawSecureClientServiceClient is the client API for DefenseClawSecureClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DefenseClaw local gRPC server contract (v1 draft).
//
// Consumed by AVC (Cisco Secure Client) over a local Unix domain socket.
// All three RPCs are server-streaming and snapshot-first: the initial
// message on each stream is the current state.
type DefenseClawSecureClientServiceClient interface {
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthSnapshot], error)
	GetStatsSnapshot(ctx context.Context, in *GetStatsSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatsSnapshot], error)
	WatchNotifications(ctx context.Context, in *WatchNotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotificationRecord], error)
}

type defenseClawSecureClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDefenseClawSecureClientServiceClient(cc grpc.ClientConnInterface) DefenseClawSecureClientServiceClient {
	return &defenseClawSecureClientServiceClient{cc}
}

func (c *defenseClawSecureClientServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DefenseClawSecureClientService_ServiceDesc.Streams[0], DefenseClawSecureClientService_GetHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetHealthRequest, HealthSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DefenseClawSecureClientService_GetHealthClient = grpc.ServerStreamingClient[HealthSnapshot]

func (c *defenseClawSecureClientServiceClient) GetStatsSnapshot(ctx context.Context, in *GetStatsSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatsSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DefenseClawSecureClientService_ServiceDesc.Streams[1], DefenseClawSecureClientService_GetStatsSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetStatsSnapshotRequest, StatsSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DefenseClawSecureClientService_GetStatsSnapshotClient = grpc.ServerStreamingClient[StatsSnapshot]

func (c *defenseClawSecureClientServiceClient) WatchNotifications(ctx context.Context, in *WatchNotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotificationRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DefenseClawSecureClientService_ServiceDesc.Streams[2], DefenseClawSecureClientService_WatchNotifications_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchNotificationsRequest, NotificationRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DefenseClawSecureClientService_WatchNotificationsClient = grpc.ServerStreamingClient[NotificationRecord]

// DefenseClawSecureClientServiceServer is the server API for DefenseClawSecureClientService service.
// All implementations must embed UnimplementedDefenseClawSecureClientServiceServer
// for forward compatibility.
//
// DefenseClaw local gRPC server contract (v1 draft).
//
// Consumed by AVC (Cisco Secure Client) over a local Unix domain socket.
// All three RPCs are server-streaming and snapshot-first: the initial
// message on each stream is the current state.
type DefenseClawSecureClientServiceServer interface {
	GetHealth(*GetHealthRequest, grpc.ServerStreamingServer[HealthSnapshot]) error
	GetStatsSnapshot(*GetStatsSnapshotRequest, grpc.ServerStreamingServer[StatsSnapshot]) error
	WatchNotifications(*WatchNotificationsRequest, grpc.ServerStreamingServer[NotificationRecord]) error
	mustEmbedUnimplementedDefenseClawSecureClientServiceServer()
}

// UnimplementedDefenseClawSecureClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDefenseClawSecureClientServiceServer struct{}

func (UnimplementedDefenseClawSecureClientServiceServer) GetHealth(*GetHealthRequest, grpc.ServerStreamingServer[HealthSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedDefenseClawSecureClientServiceServer) GetStatsSnapshot(*GetStatsSnapshotRequest, grpc.ServerStreamingServer[StatsSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method GetStatsSnapshot not implemented")
}
func (UnimplementedDefenseClawSecureClientServiceServer) WatchNotifications(*WatchNotificationsRequest, grpc.ServerStreamingServer[NotificationRecord]) error {
	return status.Errorf(codes.Unimplemented, "method WatchNotifications not implemented")
}
func (UnimplementedDefenseClawSecureClientServiceServer) mustEmbedUnimplementedDefenseClawSecureClientServiceServer() {
}
func (UnimplementedDefenseClawSecureClientServiceServer) testEmbeddedByValue() {}

// UnsafeDefenseClawSecureClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DefenseClawSecureClientServiceServer will
// result in compilation errors.
type UnsafeDefenseClawSecureClientServiceServer interface {
	mustEmbedUnimplementedDefenseClawSecureClientServiceServer()
}

func RegisterDefenseClawSecureClientServiceServer(s grpc.ServiceRegistrar, srv DefenseClawSecureClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedDefenseClawSecureClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DefenseClawSecureClientService_ServiceDesc, srv)
}

func _DefenseClawSecureClientService_GetHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DefenseClawSecureClientServiceServer).GetHealth(m, &grpc.GenericServerStream[GetHealthRequest, HealthSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DefenseClawSecureClientService_GetHealthServer = grpc.ServerStreamingServer[HealthSnapshot]

func _DefenseClawSecureClientService_GetStatsSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStatsSnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DefenseClawSecureClientServiceServer).GetStatsSnapshot(m, &grpc.GenericServerStream[GetStatsSnapshotRequest, StatsSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DefenseClawSecureClientService_GetStatsSnapshotServer = grpc.ServerStreamingServer[StatsSnapshot]

func _DefenseClawSecureClientService_WatchNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchNotificationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DefenseClawSecureClientServiceServer).WatchNotifications(m, &grpc.GenericServerStream[WatchNotificationsRequest, NotificationRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DefenseClawSecureClientService_WatchNotificationsServer = grpc.ServerStreamingServer[NotificationRecord]

// DefenseClawSecureClientService_ServiceDesc is the grpc.ServiceDesc for DefenseClawSecureClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DefenseClawSecureClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "defenseclaw.secureclient.v1.DefenseClawSecureClientService",
	HandlerType: (*DefenseClawSecureClientServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHealth",
			Handler:       _DefenseClawSecureClientService_GetHealth_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStatsSnapshot",
			Handler:       _DefenseClawSecureClientService_GetStatsSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchNotifications",
			Handler:       _DefenseClawSecureClientService_WatchNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "secureclient.proto",
}
